# Generated by Django 5.1.5 on 2026-05-25 11:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrbTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_time', models.DateTimeField()),
                ('message', models.CharField(blank=True, default='Back soon!', max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('start_time', models.DateTimeField()),
                ('currency_symbol', models.CharField(default='£', max_length=4)),
                ('is_active', models.BooleanField(default=False, help_text='Only one event can be active at a time.')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('platform', models.CharField(choices=[('NES', 'NES'), ('SNES', 'SNES'), ('N64', 'N64'), ('GC', 'GameCube'), ('Wii', 'Wii'), ('WiiU', 'Wii U'), ('Switch', 'Switch'), ('GB', 'Game Boy'), ('GBC', 'Game Boy Color'), ('GBA', 'Game Boy Advance'), ('DS', 'Nintendo DS'), ('3DS', 'Nintendo 3DS'), ('Other', 'Other')], max_length=20)),
                ('layout_type', models.CharField(choices=[('16x9', '16:9 widescreen'), ('4x3', '4:3 standard'), ('3ds', 'Nintendo 3DS'), ('ds-top', 'Nintendo DS — top screen only'), ('ds-both', 'Nintendo DS — both screens'), ('fsa-split', 'Four Swords Adventures — 4-player split')], max_length=20)),
                ('default_play_minutes', models.PositiveIntegerField(help_text='Estimated time for a rushed main-story run, in minutes.')),
                ('box_art_url', models.URLField(blank=True)),
                ('hltb_id', models.CharField(blank=True, max_length=32)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('channel_url', models.URLField(blank=True)),
                ('is_streamer', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image_url', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, help_text='e.g. "weapon", "song", "heart-piece", "key-item"', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.game')),
            ],
            options={
                'ordering': ['game', 'order', 'name'],
                'unique_together': {('game', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('planned_minutes', models.PositiveIntegerField(blank=True, help_text='Override of Game.default_play_minutes for this run.', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='api.event')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='api.game')),
                ('runners', models.ManyToManyField(blank=True, related_name='schedule_entries', to='api.runner')),
            ],
            options={
                'verbose_name_plural': 'schedule entries',
                'ordering': ['event', 'order'],
                'unique_together': {('event', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CurrentlyPlaying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_playing', to='api.scheduleentry')),
            ],
            options={
                'verbose_name_plural': 'currently playing',
            },
        ),
        migrations.CreateModel(
            name='TimerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('accumulated_seconds', models.PositiveIntegerField(default=0, help_text='Total seconds spent running excluding the current segment.')),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('schedule_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timer', to='api.scheduleentry')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('justgiving', 'JustGiving'), ('tiltify', 'Tiltify'), ('facebook', 'Facebook'), ('twitch', 'Twitch Charity'), ('paypal', 'PayPal'), ('direct', 'Direct / cash'), ('other', 'Other')], max_length=20)),
                ('donor_name', models.CharField(blank=True, default='Anonymous', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('message', models.TextField(blank=True)),
                ('donated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('external_id', models.CharField(blank=True, help_text='Platform-side ID — used to dedupe when pulling via API.', max_length=200)),
                ('gift_aid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='api.event')),
            ],
            options={
                'ordering': ['-donated_at'],
                'indexes': [models.Index(fields=['event', 'platform'], name='api_donatio_event_i_57d0ab_idx')],
                'unique_together': {('platform', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='CollectedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_in', to='api.gameitem')),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_items', to='api.scheduleentry')),
            ],
            options={
                'ordering': ['-collected_at'],
                'unique_together': {('schedule_entry', 'item')},
            },
        ),
    ]
