# Generated by Django 5.1.5 on 2026-05-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_zelda_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='igdb_id',
            field=models.CharField(blank=True, help_text='IGDB game id — lets us refresh covers/metadata without re-running the fuzzy name search.', max_length=32),
        ),
        migrations.AddField(
            model_name='game',
            name='twitch_game_id',
            field=models.CharField(blank=True, help_text='Twitch Helix game id — used to PATCH the channel category when this game starts.', max_length=32),
        ),
    ]
