# Generated by Django 5.1.5 on 2026-05-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_game_igdb_id_game_twitch_game_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('game', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(help_text='Direct MP3 URL on an OCRemix mirror. Served via /api/audio/proxy/ for CORS.', max_length=600)),
                ('ocr_id', models.CharField(blank=True, db_index=True, max_length=12)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
