# Generated by Django 5.1.5 on 2026-05-25 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_switch2_catalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='NowPlayingAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='now_playing', to='api.audiotrack')),
            ],
            options={
                'verbose_name_plural': 'now playing audio',
            },
        ),
    ]
