# Generated by Django 5.1.5 on 2026-05-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_nowplayingaudio'),
        ('api', '0006_twitchoauthtoken'),
    ]

    operations = [
    ]
