# Generated by Django 5.1.5 on 2026-05-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_0006_nowplayingaudio_0006_twitchoauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowplayingaudio',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
