# Generated by Django 5.1.5 on 2026-05-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_nowplayingaudio_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowplayingaudio',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
