# Generated by Django 5.1.5 on 2026-05-26 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_runner_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='slot_type',
            field=models.CharField(choices=[('game', 'Game'), ('start', 'Stream start'), ('meal', 'Meal break'), ('sleep', 'Sleep break'), ('break', 'Break'), ('end', 'Stream end')], default='game', max_length=16),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='title',
            field=models.CharField(blank=True, help_text='Optional label override (e.g. "Lunch with the chat"). Game slots fall back to Game.title when blank.', max_length=120),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='api.game'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='planned_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Game slots: overrides Game.default_play_minutes. Break slots: the duration of the break.', null=True),
        ),
    ]
