# Generated by Django 5.1.5 on 2026-05-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_break_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_url',
            field=models.URLField(blank=True, help_text='Wide event poster/banner (used on landing, social cards).'),
        ),
        migrations.AddField(
            model_name='event',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Square-ish event logo (used in headers, overlays).'),
        ),
    ]
