# Generated by Django 5.1.5 on 2026-05-26 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_event_branding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('justgiving', 'JustGiving'), ('tiltify', 'Tiltify'), ('facebook', 'Facebook'), ('twitch', 'Twitch Charity'), ('paypal', 'PayPal'), ('direct', 'Direct / cash'), ('other', 'Other')], max_length=20)),
                ('label', models.CharField(blank=True, help_text='Display label (e.g. "JustGiving — main page"). Falls back to the platform name when blank.', max_length=120)),
                ('url', models.URLField()),
                ('external_id', models.CharField(blank=True, help_text='Platform campaign/page id used by donation polling.', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Promotes this page above others on landing CTAs.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_pages', to='api.event')),
            ],
            options={
                'ordering': ['event', 'order', 'id'],
                'indexes': [models.Index(fields=['event'], name='api_donatio_event_i_2b996c_idx')],
            },
        ),
    ]
