# Generated by Django 5.1.5 on 2026-05-26 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_donation_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='parent_entry',
            field=models.ForeignKey(blank=True, help_text='If set, this slot overlaps the runtime of the parent entry. Used to place meal/sleep breaks during a game without displacing subsequent entries in the schedule.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_breaks', to='api.scheduleentry'),
        ),
    ]
