# Generated by Django 5.1.5 on 2026-05-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_overlap_breaks'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='start_offset_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Only meaningful when parent_entry is set: minutes into the parent game when this break begins.'),
        ),
    ]
