# Generated by Django 5.1.5 on 2026-05-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_child_break_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpage',
            name='fee_warning',
            field=models.TextField(blank=True, help_text='Shown as an inline warning banner on this row in the donation picker — non-blank surfaces a yellow callout (e.g. the JustGiving platform-fee notice).'),
        ),
        migrations.AddField(
            model_name='donationpage',
            name='fees_url',
            field=models.URLField(blank=True, help_text="Optional link to the platform's fundraising-fee page."),
        ),
        migrations.AddField(
            model_name='donationpage',
            name='gift_aid_url',
            field=models.URLField(blank=True, help_text="Optional link to the platform's Gift Aid documentation."),
        ),
    ]
