# Generated by Django 5.1.5 on 2026-05-26 10:45

from decimal import Decimal
from django.db import migrations, models


def seed_profiles_from_pages(apps, schema_editor):
    """Lift the existing per-DonationPage fees/gift-aid/warning values onto
    one DonationPlatformProfile per platform. For each platform we pick the
    page with the most-populated metadata so we don't accidentally erase data
    by choosing a blank row."""
    DonationPage = apps.get_model('api', 'DonationPage')
    Profile = apps.get_model('api', 'DonationPlatformProfile')
    by_platform: dict[str, dict] = {}
    for page in DonationPage.objects.all():
        score = (
            (1 if page.fees_url else 0)
            + (1 if page.gift_aid_url else 0)
            + (1 if page.fee_warning else 0)
        )
        current = by_platform.get(page.platform)
        if current is None or score > current['score']:
            by_platform[page.platform] = {
                'score': score,
                'fees_url': page.fees_url,
                'gift_aid_url': page.gift_aid_url,
                'fee_warning': page.fee_warning,
            }
    for platform, payload in by_platform.items():
        Profile.objects.update_or_create(
            platform=platform,
            defaults={
                'fees_url': payload['fees_url'],
                'gift_aid_url': payload['gift_aid_url'],
                'fee_warning': payload['fee_warning'],
            },
        )


def noop_reverse(apps, schema_editor):
    # Reverse migration restores empty profiles — the per-page columns will be
    # re-added by Django's RemoveField reversal, but their values are gone.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_donation_page_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPlatformProfile',
            fields=[
                ('platform', models.CharField(choices=[('justgiving', 'JustGiving'), ('tiltify', 'Tiltify'), ('facebook', 'Facebook'), ('twitch', 'Twitch Charity'), ('paypal', 'PayPal'), ('direct', 'Direct / cash'), ('other', 'Other')], max_length=20, primary_key=True, serialize=False, unique=True)),
                ('display_label', models.CharField(blank=True, help_text='Optional override for the platform display name shown in the donation picker. Falls back to the choice label.', max_length=120)),
                ('fees_url', models.URLField(blank=True, help_text="Link to the platform's fundraising-fee page.")),
                ('gift_aid_url', models.URLField(blank=True, help_text="Link to the platform's Gift Aid documentation.")),
                ('fee_warning', models.TextField(blank=True, help_text='Inline warning banner shown on the picker row when set.')),
                ('minimum_donation_amount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Smallest donation the platform accepts. Shown in the picker so donors know the floor before they click through.', max_digits=10)),
            ],
            options={
                'ordering': ['platform'],
            },
        ),
        migrations.RunPython(seed_profiles_from_pages, noop_reverse),
        migrations.RemoveField(
            model_name='donationpage',
            name='fee_warning',
        ),
        migrations.RemoveField(
            model_name='donationpage',
            name='fees_url',
        ),
        migrations.RemoveField(
            model_name='donationpage',
            name='gift_aid_url',
        ),
    ]
