# Generated by Django 5.1.5 on 2026-05-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_gameitem_image_url_charfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bloodmoon', help_text='Label shown in the control panel — purely cosmetic.', max_length=80)),
                ('primary', models.CharField(default='#e71347', help_text='Main brand accent (--theme-primary).', max_length=20)),
                ('primary_bright', models.CharField(default='#da4471', help_text='Bright variant for hover/glow (--theme-primary-bright).', max_length=20)),
                ('secondary', models.CharField(default='#731c37', help_text='Secondary / darker brand colour (--theme-secondary).', max_length=20)),
                ('background_from', models.CharField(default='#4c1324', help_text='Top stop of the page background gradient (--theme-bg-from).', max_length=20)),
                ('background_to', models.CharField(default='#1a0a10', help_text='Bottom stop of the page background gradient (--theme-bg-to).', max_length=20)),
                ('text_color', models.CharField(default='#ffffff', help_text='Default text colour (--theme-text).', max_length=20)),
                ('text_muted', models.CharField(default='rgba(255, 255, 255, 0.6)', help_text='Muted/subdued text colour (--theme-text-muted).', max_length=20)),
                ('line_color', models.CharField(default='rgba(185, 39, 83, 0.5)', help_text='Borders / dividers / lines (--theme-line).', max_length=40)),
                ('logo_url', models.URLField(blank=True, help_text='Hero / navbar wordmark. Falls back to bundled SVG when blank.')),
                ('logo_small_url', models.URLField(blank=True, help_text='Compact mark used in tight spaces (omnibar pill).')),
                ('favicon_url', models.URLField(blank=True, help_text='Browser tab icon. Blank = use the default favicon.')),
                ('background_video_url', models.URLField(blank=True, help_text='Optional looping background video for the page shell. When blank the gradient alone is shown.')),
                ('background_image_url', models.URLField(blank=True, help_text='Optional static background image used when no video is set.')),
                ('button_gradient_from', models.CharField(default='#4c1324', help_text='First stop of the primary button gradient.', max_length=20)),
                ('button_gradient_to', models.CharField(default='#b92753', help_text='Last stop of the primary button gradient.', max_length=20)),
                ('button_text_color', models.CharField(default='#ffffff', help_text='Button label colour.', max_length=20)),
                ('button_border_color', models.CharField(default='rgba(255, 255, 255, 0.4)', help_text='Default border colour around buttons.', max_length=40)),
                ('divider_thickness', models.PositiveSmallIntegerField(default=2, help_text='Decorative divider/line thickness in pixels.')),
                ('heading_font', models.CharField(default="'Bungee', sans-serif", help_text='Heading font-family stack (--theme-font-heading).', max_length=80)),
                ('body_font', models.CharField(default="'Open Sans', sans-serif", help_text='Body font-family stack (--theme-font-body).', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Theme',
            },
        ),
    ]
