# Generated by Django 5.1.5 on 2026-05-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_theme_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='text_muted',
            field=models.CharField(default='rgba(255, 255, 255, 0.6)', help_text='Muted/subdued text colour (--theme-text-muted).', max_length=40),
        ),
    ]
