# Generated by Django 5.1.5 on 2026-05-26 16:49

from django.db import migrations, models


def promote_existing_row_to_active(apps, schema_editor):
    """The singleton row that existed before this migration (pk=1) becomes
    the first active theme in the library — that way /api/theme/ keeps
    returning what it returned before."""
    Theme = apps.get_model('api', 'ThemeSettings')
    existing = Theme.objects.first()
    if existing:
        existing.is_active = True
        existing.save()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_theme_settings_widen_muted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themesettings',
            options={'ordering': ['-is_active', 'name'], 'verbose_name': 'Theme', 'verbose_name_plural': 'Themes'},
        ),
        migrations.AddField(
            model_name='themesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only one theme can be active at a time. The active row is what /api/theme/ returns to the frontend.'),
        ),
        migrations.RunPython(promote_existing_row_to_active, noop_reverse),
    ]
