# Generated by Django 5.1.5 on 2026-05-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_theme_multi_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='image_hue_rotate',
            field=models.IntegerField(default=-50, help_text='Degrees to rotate hue of decorative images (carousel photos, etc.) so they tint to the theme. e.g. -50 = bloodmoon red, +180 = teal/blue, 0 = sepia neutral.'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='link_color',
            field=models.CharField(default='#ffc2e0', help_text='Inline anchor colour (--theme-link).', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='link_hover_color',
            field=models.CharField(default='#ffffff', help_text='Inline anchor hover colour (--theme-link-hover).', max_length=40),
        ),
    ]
