# Generated by Django 5.1.5 on 2026-05-27 03:29

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_theme_golden_goddess'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='omnibar_layout',
            field=models.JSONField(blank=True, default=dict, help_text='Per-event omnibar lane composition. Shape: { "lanes": [{ "id": "top", "mode": "rotating|pinned", "intervalMs": 12000, "panels": ["current-game", ...] }] }. Empty dict falls back to the default layout in frontend/src/routes/obs/omnibar/hooks/useLayoutConfig.ts.'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='current_objective',
            field=models.CharField(blank=True, help_text='Operator-set free text describing what the runner is trying to do RIGHT NOW (e.g. "Find the Master Sword", "Beat Ganondorf, second phase"). Surfaced in the omnibar ObjectivePanel when set; hidden when blank.', max_length=240),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='was_skipped',
            field=models.BooleanField(default=False, help_text='Operator marked the entry as abandoned without completing. Distinct from is_completed — both are terminal states but the omnibar treats them differently (skipped: muted, completed: celebration).'),
        ),
        migrations.CreateModel(
            name='ExternalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=32)),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['source', 'kind', '-occurred_at'], name='api_externa_source_4aac40_idx')],
            },
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('reached_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Reserved for future extensions (bid-war options, tiered rewards). Frontend reads kind-specific keys where defined.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='api.event')),
                ('schedule_entry', models.ForeignKey(blank=True, help_text='When set, this incentive is only shown while this schedule entry is the active playthrough.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incentives', to='api.scheduleentry')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('threshold_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('celebration_message', models.TextField(blank=True, help_text='Surfaced on the omnibar when the milestone is hit. Markdown not supported — plain text only.')),
                ('reached_at', models.DateTimeField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, help_text='Optional fanfare audio. The OBS browser source plays this once when the milestone is crossed.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='api.event')),
            ],
            options={
                'ordering': ['threshold_amount'],
            },
        ),
        migrations.CreateModel(
            name='OmnibarOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, help_text='Open string. Conventional values: urgent, announcement, sponsor-shout, raid-alert, raffle.', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('priority', models.SmallIntegerField(default=0, help_text='Higher wins when multiple overrides overlap.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', '-starts_at'],
                'indexes': [models.Index(fields=['is_active', 'expires_at'], name='api_omnibar_is_acti_e4a185_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlaythroughEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, help_text='Open string. Conventional values: boss-defeated, shrine-cleared, item-collected, player-death, segment-complete, runner-swap. New kinds can be introduced by inserting a row — the frontend will fall through to a generic handler until a specific one is registered.', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text="When non-null, the omnibar will not replay this event after this timestamp. Used to bound the replay window so a freshly-mounted browser source doesn't fire ten minutes of stale animations.", null=True)),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.scheduleentry')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['schedule_entry', '-created_at'], name='api_playthr_schedul_ac447f_idx')],
            },
        ),
    ]
