# Generated by Django 5.1.5 on 2026-05-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_omnibar_v2_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='omnibaroverride',
            name='target_lane',
            field=models.CharField(choices=[('top', 'Top lane'), ('bottom', 'Bottom lane'), ('both', 'Both lanes')], default='bottom', help_text='Which omnibar lane takes the override banner. Top is the status zone (current game / playtime); bottom is the rotating ticker zone. Both mirrors the banner across both lanes for a full-bar takeover.', max_length=8),
        ),
    ]
