# Generated by Django 5.1.5 on 2026-05-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_tts_replay'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='setpiece_kind',
            field=models.CharField(blank=True, help_text='Open string for the type of set-piece in progress: "boss", "shrine", "dungeon", "cutscene", anything the operator declares. Blank = no set-piece active.', max_length=32),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='setpiece_name',
            field=models.CharField(blank=True, help_text='Display name for the set-piece (e.g. "Ganondorf"). Surfaced by the omnibar SetpiecePanel.', max_length=120),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='setpiece_stage',
            field=models.CharField(blank=True, choices=[('', 'Inactive'), ('imminent', 'Imminent — build-up'), ('active', 'Active — in progress')], default='', help_text='Operator-controlled lifecycle of the current set-piece. Blank = none. Defeated is signalled via a PlaythroughEvent (boss-defeated etc.) which clears these fields too.', max_length=16),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='setpiece_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttsreplay',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
