# Generated by Django 5.1.5 on 2026-05-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_tts_now_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='omnibar_layout',
            field=models.JSONField(blank=True, default=dict, help_text='Per-game omnibar layout override. Same shape as Event.omnibar_layout. When this game is the active playthrough, its lane configs win over the event-level layout. Blank dict → fall back to the event layout.'),
        ),
        migrations.AlterField(
            model_name='chestannouncersettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ttsnowreading',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
