# Generated by Django 5.1.5 on 2026-05-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_donation_mute_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chestannouncersoundtrigger',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
