# Generated by Django 5.1.5 on 2026-05-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_chestannouncersoundtrigger_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharitySlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('logo', 'Logo'), ('blurb', 'Blurb')], default='blurb', max_length=8)),
                ('title', models.CharField(blank=True, help_text='Blurb header (uppercase gold line). Ignored for logos.', max_length=80)),
                ('body', models.CharField(blank=True, help_text='Blurb body text. Ignored for logos.', max_length=240)),
                ('image_url', models.CharField(blank=True, help_text='Logo image URL. Absolute or site-relative. Ignored for blurbs.', max_length=500)),
                ('alt_text', models.CharField(blank=True, help_text='Logo alt text (e.g. "SpecialEffect"). Ignored for blurbs.', max_length=80)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the rotation (lower = earlier).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
