# Generated by Django 5.1.5 on 2026-05-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_chest_announcer_card_hold_ms'),
        ('api', '0041_seed_charity_blurbs'),
    ]

    operations = [
    ]
