# Generated by Django 5.1.5 on 2026-05-28 23:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_game_asset_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('image_url', models.CharField(blank=True, help_text='Absolute URL or site-relative path to an objective sprite (e.g. /assets/img/game-franchise/legend-of-zelda/oot/items/Triforce.png).', max_length=500)),
                ('category', models.CharField(blank=True, help_text='e.g. "story", "side-quest", "100%", "boss".', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['game', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntryObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('obtained', 'Obtained'), ('skipped', 'Skipped (not needed this run)')], max_length=12)),
                ('obtained_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-obtained_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='scheduleentrysoundtrigger',
            new_name='api_schedul_is_acti_a09f5d_idx',
            old_name='api_schedu_is_acti_idx',
        ),
        migrations.AlterField(
            model_name='chestannouncersoundtrigger',
            name='match',
            field=models.CharField(blank=True, help_text='amount: JS regex tested against the bare amount string (e.g. "69.00"). Currency glyphs in the pattern are stripped automatically, so "^£69\\.00$" works the same as "^69\\.00$". "69" matches anything containing the digits "69"; "^69\\.00$" matches exactly 69.00; "\\.69$" matches any amount ending in 69 pence. keyword: comma-separated terms, case-insensitive substring of the donation message. game: leave blank, the `game` FK below drives the match.', max_length=200),
        ),
        migrations.AlterField(
            model_name='chestreplay',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scheduleentrysoundtrigger',
            name='subhead',
            field=models.CharField(blank=True, help_text='Optional smaller text shown beneath the headline on the celebration banner. Ignored when `show_banner` is false. Use for context like "Charity break · 15 min" under a "BREAK STARTING" headline.', max_length=240),
        ),
        migrations.AddField(
            model_name='gameobjective',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='api.game'),
        ),
        migrations.AddField(
            model_name='scheduleentryobjective',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_statuses', to='api.gameobjective'),
        ),
        migrations.AddField(
            model_name='scheduleentryobjective',
            name='schedule_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_statuses', to='api.scheduleentry'),
        ),
        migrations.AlterUniqueTogether(
            name='gameobjective',
            unique_together={('game', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='scheduleentryobjective',
            unique_together={('schedule_entry', 'objective')},
        ),
    ]
