# Generated by Django 5.1.5 on 2026-05-29, then hand-ordered so the data
# migration (link_group → GameItemSet) runs while the old fields still exist.

import django.db.models.deletion
from django.db import migrations, models


def populate_sets(apps, schema_editor):
    """Migrate the legacy single `link_group`/`link_kind` into the new
    per-game GameItemSet table + M2M. Each distinct non-empty link_group
    becomes one set (kind taken from the first member that declares one);
    every item carrying that link_group is linked to it."""
    GameItem = apps.get_model('api', 'GameItem')
    GameItemSet = apps.get_model('api', 'GameItemSet')
    seen = {}  # (game_id, name) -> GameItemSet
    for item in GameItem.objects.exclude(link_group='').iterator():
        name = (item.link_group or '').strip()
        if not name:
            continue
        key = (item.game_id, name)
        s = seen.get(key)
        if s is None:
            s, _ = GameItemSet.objects.get_or_create(
                game_id=item.game_id,
                name=name,
                defaults={'kind': item.link_kind or 'set', 'order': 0},
            )
            seen[key] = s
        item.sets.add(s)


def noop_reverse(apps, schema_editor):
    # Irreversible-ish: dropping the sets back into link_group isn't worth it.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_gameitem_countable_collecteditem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameItemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('kind', models.CharField(choices=[('upgrade', 'Upgrade chain'), ('trade', 'Trade sequence'), ('set', 'Related set')], default='set', help_text='How members relate: an ordered upgrade chain, an ordered trade sequence, or an unordered related set.', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_sets', to='api.game')),
            ],
            options={
                'ordering': ['game', 'order', 'name'],
                'unique_together': {('game', 'name')},
            },
        ),
        migrations.AddField(
            model_name='gameitem',
            name='sets',
            field=models.ManyToManyField(blank=True, help_text='Families this item belongs to (e.g. a medallion is in both "Medallions" and "Magic Items"). Rendered as a cluster per set.', related_name='items', to='api.gameitemset'),
        ),
        migrations.RunPython(populate_sets, noop_reverse),
        migrations.RemoveField(
            model_name='gameitem',
            name='link_group',
        ),
        migrations.RemoveField(
            model_name='gameitem',
            name='link_kind',
        ),
    ]
