# Generated by Django 5.1.5 on 2026-05-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_gameitem_unlocks_with_starts_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='timer_segment_ids',
            field=models.JSONField(blank=True, default=list, help_text="Ordered GameObjective ids forming this run's LiveSplit route (the timer splits). Empty = fall back to all of the game's objectives in their library order."),
        ),
    ]
