# Generated by Django 5.1.5 on 2026-05-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_scheduleentry_timer_segment_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameobjective',
            name='group',
            field=models.CharField(blank=True, help_text='Optional run-section label used to cluster objectives in the library editor and the timer splits (e.g. "Prologue", "The Dark World", "Endgame"). Falls back to category when blank.', max_length=60),
        ),
    ]
