# Generated by Django 5.1.5 on 2026-05-29 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_gameobjective_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameobjective',
            name='linked_item',
            field=models.ForeignKey(blank=True, help_text='For "item get" objectives: the GameItem whose collection completes this objective. Collecting the item marks the objective obtained for the run, and marking the objective obtained collects the item (kept in lockstep per run).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_objectives', to='api.gameitem'),
        ),
    ]
