# Generated by Django 5.1.5 on 2026-05-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_gameobjective_linked_item'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameobjective',
            unique_together={('game', 'name', 'group')},
        ),
    ]
