# Generated by Django 5.1.5 on 2026-05-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_alter_gameobjective_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameitem',
            unique_together={('game', 'name', 'group')},
        ),
    ]
