# Generated by Django 5.1.5 on 2026-05-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_theme_snes_pal_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='accent_1',
            field=models.CharField(blank=True, default='', help_text='Optional accent #1 (--theme-accent-1). Used for the success/positive register on badges and decorative stripes. Blank falls back to primary_bright at runtime.', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='accent_2',
            field=models.CharField(blank=True, default='', help_text='Optional accent #2 (--theme-accent-2). Used for the warning/caution register. Blank falls back to primary.', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='accent_3',
            field=models.CharField(blank=True, default='', help_text='Optional accent #3 (--theme-accent-3). Used for the danger/attention register. Blank falls back to secondary.', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_lane_bg',
            field=models.CharField(blank=True, default='', help_text='Solid fill for the omnibar lane (--theme-omnibar-lane-bg). Blank keeps the baked-in steel gradient. Useful for bright themes that want the bar to match the page.', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_tag_color',
            field=models.CharField(blank=True, default='', help_text='Tag pill / brand cluster accent (--theme-omnibar-tag). Blank lets --obs-accent (the per-game accent) keep driving it.', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_ticker_accent',
            field=models.CharField(blank=True, default='', help_text='Ticker / divider accent on the bottom lane (--theme-omnibar-ticker). Blank falls back to primary_bright.', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='surface_border_color',
            field=models.CharField(blank=True, default='', help_text='Card/panel edge colour (--theme-surface-border). Blank falls back to line_color.', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='surface_color',
            field=models.CharField(default='rgba(0, 0, 0, 0.35)', help_text='Card/panel fill (--theme-surface). Bright themes can set a solid light value here; the default semi-transparent black preserves the bloodmoon look on dark themes.', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='surface_text_color',
            field=models.CharField(blank=True, default='', help_text='Text colour on surface (--theme-surface-text). Blank falls back to text_color, which is correct for dark surfaces; bright surfaces should set a dark value here.', max_length=40),
        ),
    ]
