# Generated by Django 5.1.5 on 2026-05-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_theme_snes_multicolour_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_bottom_tag_from',
            field=models.CharField(blank=True, default='', help_text='Top stop of the bottom-lane tag pill gradient (--theme-omnibar-bottom-tag-from). Drives every panel in the bottom lane (donation reel, charity info, schedule, etc.).', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_bottom_tag_to',
            field=models.CharField(blank=True, default='', help_text='Bottom stop of the bottom-lane tag pill gradient (--theme-omnibar-bottom-tag-to).', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_brand_from',
            field=models.CharField(blank=True, default='', help_text='Top stop of the left-side logo / brand-pill gradient (--theme-omnibar-brand-from).', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_brand_to',
            field=models.CharField(blank=True, default='', help_text='Bottom stop of the left-side logo / brand-pill gradient (--theme-omnibar-brand-to).', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_top_tag_from',
            field=models.CharField(blank=True, default='', help_text='Top stop of the top-lane tag pill gradient (--theme-omnibar-top-tag-from). Drives every panel in the top lane.', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_top_tag_to',
            field=models.CharField(blank=True, default='', help_text='Bottom stop of the top-lane tag pill gradient (--theme-omnibar-top-tag-to).', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_total_from',
            field=models.CharField(blank=True, default='', help_text='Top stop of the right-side total-raised / charity cluster gradient (--theme-omnibar-total-from).', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_total_to',
            field=models.CharField(blank=True, default='', help_text='Bottom stop of the right-side total-raised / charity cluster gradient (--theme-omnibar-total-to).', max_length=40),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='omnibar_tag_color',
            field=models.CharField(blank=True, default='', help_text='[Deprecated] Global tag-pill / brand cluster accent — used as the fallback default for the per-section gradient fields below when those are blank. Prefer setting omnibar_brand_from / top_tag_from / etc. for full control. Blank lets --obs-accent (the per-game accent) drive everything.', max_length=40),
        ),
    ]
