# Generated by Django 5.1.5 on 2026-05-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_theme_snes_omnibar_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_bottom_tag_text',
            field=models.CharField(blank=True, default='', help_text='Text colour for the bottom lane — both the tag pill label and the panel body content (--theme-omnibar-bottom-text). Blank falls back to text_color.', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_brand_text',
            field=models.CharField(blank=True, default='', help_text='Text colour on the left-side logo / brand pill (--theme-omnibar-brand-text). Blank falls back to text_color.', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_top_tag_text',
            field=models.CharField(blank=True, default='', help_text='Text colour for the top lane — both the tag pill label and the panel body content (--theme-omnibar-top-text). Blank falls back to text_color.', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_total_text',
            field=models.CharField(blank=True, default='', help_text='Text colour inside the right-side total-raised / charity cluster — currency + amount + supporting copy (--theme-omnibar-total-text). Blank falls back to text_color.', max_length=40),
        ),
    ]
