# Generated by Django 5.1.5 on 2026-05-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_theme_snes_section_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_bottom_lane_text',
            field=models.CharField(blank=True, default='', help_text='Text colour for the BOTTOM-LANE BODY content (--theme-omnibar-bottom-lane-text). Drives the panel content sitting to the right of the bottom tag. Blank falls back to text_color.', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_top_lane_text',
            field=models.CharField(blank=True, default='', help_text='Text colour for the TOP-LANE BODY content (--theme-omnibar-top-lane-text). Drives .ob-text-strong / .ob-text-muted inside the top lane, i.e. the panel content sitting to the right of the tag. Blank falls back to text_color.', max_length=40),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='omnibar_bottom_tag_text',
            field=models.CharField(blank=True, default='', help_text='Text colour for the BOTTOM-LANE TAG PILL ONLY (--theme-omnibar-bottom-tag-text). Blank falls back to omnibar_bottom_lane_text → text_color.', max_length=40),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='omnibar_top_tag_text',
            field=models.CharField(blank=True, default='', help_text='Text colour for the TOP-LANE TAG PILL ONLY (--theme-omnibar-top-tag-text). The pill sits on the gradient so the contrast register often differs from the body content behind it. Blank falls back to omnibar_top_lane_text → text_color.', max_length=40),
        ),
    ]
