# Generated by Django 5.1.5 on 2026-05-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_theme_snes_lane_body_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_celebration_heading',
            field=models.CharField(blank=True, default='', help_text='Default celebration headline colour (--theme-omnibar-celebration-heading). Blank falls back to the original warm-gold (#ffe69b).', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_celebration_sub',
            field=models.CharField(blank=True, default='', help_text='Default celebration subhead colour (--theme-omnibar-celebration-sub). Blank inherits from the surrounding lane / fullbar text colour.', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_celebration_tag',
            field=models.CharField(blank=True, default='', help_text='Default tag pill colour during a celebration takeover (--theme-omnibar-celebration-tag). Blank lets the baked-in gold-flash mood drive it.', max_length=40),
        ),
    ]
