# Generated by Django 5.1.5 on 2026-05-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_theme_omnibar_celebration_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_celebration_flash',
            field=models.CharField(blank=True, default='', help_text='Default top-anchored flash overlay colour during a celebration takeover (--theme-omnibar-celebration-flash). The CSS gradient mixes this colour with transparent at three alpha stops, so any solid hex / rgb value works. Blank falls back to the baked-in gold (#ffd23a).', max_length=40),
        ),
    ]
