# Generated by Django 5.1.5 on 2026-05-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_theme_omnibar_celebration_flash'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_celebration_tag_from',
            field=models.CharField(blank=True, default='', help_text='Top stop of the celebration tag pill gradient (--theme-omnibar-celebration-tag-from). Blank falls back to omnibar_celebration_tag → brand mesh.', max_length=40),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_celebration_tag_to',
            field=models.CharField(blank=True, default='', help_text='Bottom stop of the celebration tag pill gradient (--theme-omnibar-celebration-tag-to). Blank falls back to omnibar_celebration_tag → brand mesh.', max_length=40),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='omnibar_celebration_tag',
            field=models.CharField(blank=True, default='', help_text='[Deprecated] Single-colour default for the celebration tag pill — kept as the fallback for omnibar_celebration_tag_from/_to when those are blank. Prefer setting the gradient pair below.', max_length=40),
        ),
    ]
