# Generated by Django 5.1.5 on 2026-05-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_theme_celebration_tag_gradient'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='mission_tagline',
            field=models.CharField(blank=True, help_text="One-line condensed mission for tight spaces — the omnibar charity ticker uses this so the long mission_statement doesn't scroll forever. Falls back to mission_statement when blank.", max_length=160),
        ),
    ]
