# Generated by Django 5.1.5 on 2026-05-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_charity_mission_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='omnibar_logo_url',
            field=models.CharField(blank=True, help_text='Wordmark shown specifically inside the omnibar brand pill. Lets the broadcast layer carry a different mark from the site hero (e.g. a white-on-coloured variant tuned to whichever brand-pill gradient the theme uses). Blank falls back to logo_url. Absolute URL or site-relative path (e.g. /assets/img/foo.svg).', max_length=500),
        ),
    ]
