# Generated by Django 5.1.5 on 2026-05-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_theme_omnibar_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchoauthtoken',
            name='scopes',
            field=models.TextField(blank=True),
        ),
    ]
