# Generated by Django 5.1.5 on 2026-05-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_alter_twitchoauthtoken_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='flash_color',
            field=models.CharField(blank=True, default='', help_text='Top-anchored flash overlay colour. Sent as payload.flash_color — the banner mixes it at three alpha stops so any solid hex / rgb value works.', max_length=40),
        ),
        migrations.AddField(
            model_name='milestone',
            name='heading_color',
            field=models.CharField(blank=True, default='', help_text='Headline (WaveText) colour during the celebration. Sent as payload.heading_color.', max_length=40),
        ),
        migrations.AddField(
            model_name='milestone',
            name='sub_color',
            field=models.CharField(blank=True, default='', help_text='Subhead (italic line under the headline) colour. Sent as payload.sub_color.', max_length=40),
        ),
        migrations.AddField(
            model_name='milestone',
            name='tag_color_from',
            field=models.CharField(blank=True, default='', help_text='Top stop of the celebration tag pill gradient. Sent to the banner as payload.tag_color_from. Pair with tag_color_to to get a gradient; either alone falls through to the theme default.', max_length=40),
        ),
        migrations.AddField(
            model_name='milestone',
            name='tag_color_to',
            field=models.CharField(blank=True, default='', help_text='Bottom stop of the celebration tag pill gradient.', max_length=40),
        ),
    ]
