# Generated by Django 5.1.5 on 2026-05-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_milestone_celebration_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowplayingaudio',
            name='visualiser_style',
            field=models.CharField(default='bars', max_length=20),
        ),
    ]
