# Generated by Django 5.1.5 on 2026-05-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_nowplayingaudio_visualiser_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.CharField(choices=[('operator-action', 'Operator action'), ('event-trigger', 'Event trigger'), ('sound-trigger', 'Sound trigger'), ('webhook', 'Webhook'), ('external-event', 'External event'), ('system', 'System')], db_index=True, max_length=24)),
                ('action', models.CharField(help_text="Slug verb, e.g. 'timer.start', 'override.create', 'sound-trigger.fired', 'webhook.justgiving.ingest'.", max_length=64)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=8)),
                ('summary', models.CharField(help_text='One-line human summary.', max_length=300)),
                ('source', models.CharField(default='system', help_text="Origin: 'operator', 'system', 'twitch', 'justgiving', …", max_length=32)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict, help_text='Sanitised request body / payload / error context.')),
                ('request_method', models.CharField(blank=True, max_length=8)),
                ('request_path', models.CharField(blank=True, max_length=300)),
                ('status_code', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', '-created_at'], name='api_activit_categor_dde5a3_idx'), models.Index(fields=['level', '-created_at'], name='api_activit_level_9fb167_idx')],
            },
        ),
    ]
