# Generated by Django 5.1.5 on 2026-05-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When an operator dismissed this entry from the queue\'s failed lane. The row stays in the audit trail — this only clears it from the live "needs attention" view.', null=True),
        ),
    ]
