# Generated by Django 5.1.5 on 2026-05-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_activitylog_acknowledged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentryobjective',
            name='split_ms',
            field=models.PositiveBigIntegerField(blank=True, help_text='Cumulative run time (milliseconds) at the moment this objective was split/obtained — the LiveSplit "split time". Null for skipped/outstanding objectives.', null=True),
        ),
    ]
