# Generated by Django 5.1.5 on 2026-05-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_scheduleentryobjective_split_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerrun',
            name='accumulated_ms',
            field=models.PositiveBigIntegerField(default=0, help_text='Total MILLISECONDS spent running excluding the current segment. Source of truth for the centisecond display; accumulated_seconds is kept in sync (= accumulated_ms // 1000) for the omnibar, which only needs whole seconds.'),
        ),
    ]
