# Generated by Django 5.1.5 on 2026-05-31 19:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_timerrun_accumulated_ms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='setpiece_kind',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='setpiece_name',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='setpiece_stage',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='setpiece_started_at',
        ),
        migrations.AddField(
            model_name='gameobjective',
            name='clears_setpiece',
            field=models.CharField(blank=True, help_text='Name of a setpiece this objective marks CLEARED when obtained — e.g. a dungeon\'s key item or boss-defeat closing the dungeon. A dungeon clears once ALL objectives targeting its name are obtained (handles "item and/or boss, or both").', max_length=120),
        ),
        migrations.AddField(
            model_name='gameobjective',
            name='setpiece_name',
            field=models.CharField(blank=True, help_text='Display name + linkage key of the setpiece this objective drives via setpiece_role (e.g. "Forest Temple", "Phantom Ganon"). Objectives sharing a name drive the same setpiece.', max_length=120),
        ),
        migrations.AddField(
            model_name='gameobjective',
            name='setpiece_role',
            field=models.CharField(blank=True, choices=[('', '— none —'), ('dungeon-enter', 'Enter dungeon (→ dungeon active)'), ('boss-enter', 'Enter boss arena (→ boss active, no alert)'), ('boss-defeat', 'Defeat boss (→ clears boss, fires alert)')], help_text='Role this objective plays in setpiece automation. "Enter dungeon"/"Enter boss arena" flip the named setpiece to active when obtained; the objective BEFORE one of these flips it to imminent. "Defeat boss" clears the named boss setpiece and fires a celebration.', max_length=40),
        ),
        migrations.CreateModel(
            name='Setpiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(help_text='Type of setpiece: "boss", "dungeon", "shrine", "cutscene", or anything the operator declares.', max_length=32)),
                ('name', models.CharField(help_text='Display name (e.g. "Phantom Ganon"). For auto rows this also keys the setpiece to its driving objectives.', max_length=120)),
                ('stage', models.CharField(choices=[('imminent', 'Imminent — build-up'), ('active', 'Active — in progress')], max_length=16)),
                ('priority', models.IntegerField(default=50, help_text='Higher = surfaced first on the omnibar. Defaults by kind; operator "pin to top" sets 1000.')),
                ('is_auto', models.BooleanField(default=False, help_text='True = derived from objective statuses and reconciled automatically; False = bespoke operator entry.')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setpieces', to='api.scheduleentry')),
            ],
            options={
                'ordering': ['-priority', '-started_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_auto', True)), fields=('schedule_entry', 'name'), name='uniq_auto_setpiece_per_entry')],
            },
        ),
    ]
