# Generated by Django 5.1.5 on 2026-05-31 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_remove_scheduleentry_setpiece_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameobjective',
            name='link_mode',
            field=models.CharField(choices=[('single', 'Single (one per dungeon)'), ('tally', 'Tally (count per dungeon, e.g. small keys)')], default='single', help_text='How a linked dungeon item resolves when collected while a dungeon setpiece is active: "single" = obtained once; "tally" = a per-dungeon count (e.g. small keys). Only meaningful for items linked by more than one objective.', max_length=8),
        ),
        migrations.AddField(
            model_name='scheduleentryobjective',
            name='count',
            field=models.PositiveIntegerField(default=0, help_text='Per-dungeon tally for link_mode=tally objectives (e.g. small keys collected in this dungeon). 0 for single/normal objectives.'),
        ),
    ]
