# Generated by Django 5.1.5 on 2026-06-01 11:20

from django.db import migrations, models


def _drop_auto_setpieces(apps, schema_editor):
    """Delete existing auto setpiece rows before the new (entry, source_key)
    constraint is added — legacy auto rows all have source_key='' so two per
    entry would collide. They're transient live state, re-derived on the next
    objective change by views.recompute_setpieces."""
    Setpiece = apps.get_model('api', 'Setpiece')
    Setpiece.objects.filter(is_auto=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_gameobjective_link_mode_scheduleentryobjective_count'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='setpiece',
            name='uniq_auto_setpiece_per_entry',
        ),
        migrations.AddField(
            model_name='setpiece',
            name='source_key',
            field=models.CharField(blank=True, default='', help_text='Internal identity for auto rows = setpiece name + driving run-section group, so the same display name can recur across dungeons (e.g. "Armos Knights" in two dungeons) as independent setpieces. Blank for bespoke operator rows.', max_length=200),
        ),
        migrations.AlterField(
            model_name='setpiece',
            name='name',
            field=models.CharField(help_text='Display name (e.g. "Phantom Ganon"). Shown on the omnibar.', max_length=120),
        ),
        migrations.RunPython(_drop_auto_setpieces, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='setpiece',
            constraint=models.UniqueConstraint(condition=models.Q(('is_auto', True)), fields=('schedule_entry', 'source_key'), name='uniq_auto_setpiece_per_entry'),
        ),
    ]
