# Generated by Django 5.1.5 on 2026-06-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_chestannouncersettings_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='death_count',
            field=models.PositiveIntegerField(default=0, help_text="Player deaths during this game, bumped from the Stream Deck via the timer-hotkey death-inc/death-dec actions. The omnibar death-count panel shows this per-game and sums it across the event's entries for a running total."),
        ),
    ]
