# Generated by Django 5.1.5 on 2026-06-02 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_scheduleentry_death_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_issuers', models.TextField(blank=True, help_text='Trusted Clerk issuer URLs, one per line or comma-separated. List both the dev and prod instances so localhost and the public site both authenticate, e.g.\nhttps://your-app.clerk.accounts.dev\nhttps://clerk.zeldathon.co.uk\nThe JWKS for each is derived as <issuer>/.well-known/jwks.json. Blank uses the CLERK_ISSUERS / CLERK_ISSUER env vars.')),
                ('clerk_authorized_parties', models.TextField(blank=True, help_text='Allowed azp claim values (the frontend origins), one per line or comma-separated. List every origin across instances, e.g. http://localhost:5173, https://www.zeldathon.co.uk')),
                ('clerk_secret_key', models.CharField(blank=True, help_text='Reserved for the Clerk Management API. Stored server-side; never exposed to the frontend.', max_length=255)),
                ('timer_hotkey_secret', models.CharField(blank=True, help_text='Shared secret the Stream Deck sends as the X-Hotkey-Secret header to /api/timer-hotkey/.', max_length=255)),
                ('web_origins', models.TextField(blank=True, help_text='Full origins (scheme + host) allowed to call this API from a browser (CORS), one per line or comma-separated. e.g. https://www.zeldathon.co.uk. Added on top of the env-driven CORS_ALLOWED_ORIGINS; takes effect immediately (no restart).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auth & access settings',
                'verbose_name_plural': 'Auth & access settings',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_user_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('operator', 'Operator')], default='viewer', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['email', 'clerk_user_id'],
            },
        ),
    ]
