# Generated by Django 5.1.5 on 2026-06-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_authconfig_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clerk_issuer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
