# Generated by Django 5.1.5 on 2026-06-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_profile_clerk_issuer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label shown in /control/layouts — purely cosmetic.', max_length=100)),
                ('layout_type', models.CharField(choices=[('16x9', '16:9 widescreen'), ('4x3', '4:3 standard'), ('3ds', 'Nintendo 3DS'), ('ds-top', 'Nintendo DS — top screen only'), ('ds-both', 'Nintendo DS — both screens'), ('fsa-split', 'Four Swords Adventures — 4-player split')], max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='One active preset per layout_type. The active row drives /obs/full for games of that aspect ratio.')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Variant + per-region widths + per-region element lists. Shape owned by the frontend parser; unknown ids are dropped and over-budget widths clamped to the 1920×984 stage on read.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Layout preset',
                'verbose_name_plural': 'Layout presets',
                'ordering': ['layout_type', '-is_active', 'name'],
            },
        ),
    ]
