# Generated by Django 5.1.5 on 2026-06-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_seed_default_4x3_layout_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameitemset',
            name='show_in_overlay',
            field=models.BooleanField(default=True, help_text="When false, this set (and items whose only sets are hidden) is omitted from the /obs/full items element — e.g. bottle contents that the broadcast doesn't need to surface."),
        ),
    ]
