# Generated by Django 5.1.5 on 2026-06-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_gameitemset_show_in_overlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='item_group_order',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of item GROUP labels (the section headers on /control/items). Drives section order on the control grid and the /obs items overlay. Labels not present fall back to first-appearance order after the listed ones.'),
        ),
    ]
