# Generated by Django 5.1.5 on 2026-06-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_seed_layout_arrangements'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutGuideSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_guide', models.BooleanField(default=False, help_text='When true, OBS layout pages draw the capture alignment guide (hashed border + device label). Toggled from /control/layouts; leave off for the live scene.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Layout guide settings',
                'verbose_name_plural': 'Layout guide settings',
            },
        ),
    ]
