# Generated by Django 5.1.5 on 2026-06-03 16:51

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_layoutguidesettings_forced_layout_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchCharityCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=200, unique=True)),
                ('broadcaster_id', models.CharField(blank=True, max_length=64)),
                ('charity_name', models.CharField(blank=True, max_length=200)),
                ('charity_logo_url', models.URLField(blank=True)),
                ('charity_website', models.URLField(blank=True)),
                ('charity_description', models.TextField(blank=True)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Twitch charity campaign',
                'ordering': ['-started_at'],
            },
        ),
    ]
