# Generated by Django 5.1.5 on 2026-06-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_twitchcharitycampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchCharityChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(help_text='Twitch channel login (lowercase, the bit after twitch.tv/).', max_length=50, unique=True)),
                ('broadcaster_id', models.CharField(blank=True, help_text='Numeric Twitch user id, resolved from the token at login.', max_length=64)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('access_token', models.CharField(blank=True, max_length=200)),
                ('refresh_token', models.CharField(blank=True, max_length=200)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to stop polling / registering EventSub for this channel without deleting its token.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Twitch charity channel',
                'ordering': ['login'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='source_channel',
            field=models.CharField(blank=True, db_index=True, help_text='For multi-channel platforms (Twitch Charity), the broadcaster login the donation came through (e.g. "zeldathonuk", "msec"). Blank for single-source platforms. Donations still merge into the same event total; this tags which channel raised them.', max_length=50),
        ),
    ]
