# Generated by Django 5.1.5 on 2026-06-04 06:48

import django.db.models.deletion
from django.db import migrations, models

# Default message per trigger (kept in sync with api.chat.DEFAULT_TEMPLATES).
# Inlined here so the data migration doesn't import app code.
_DEFAULTS = {
    'donation': '🎉 {donor} just donated {currency}{amount}! Thank you so much! 💜',
    'milestone': '🏆 Milestone reached: {milestone} ({currency}{threshold})! Thank you all! 💜',
    'game_change': '🎮 Now playing: {game}!',
    'sub': '💜 Thanks for the sub, {user}!',
    'follow': '👋 Welcome {user} — thanks for the follow!',
    'raid': '🚨 Raid incoming! Welcome {user} and the {viewers} raiders!',
    'cheer': '✨ Thanks for the {bits} bits, {user}!',
    'redemption': '🎁 {user} redeemed {reward}!',
}


def seed_defaults(apps, schema_editor):
    Event = apps.get_model('api', 'Event')
    ChatAnnouncement = apps.get_model('api', 'ChatAnnouncement')
    for event in Event.objects.all():
        for trigger, template in _DEFAULTS.items():
            ChatAnnouncement.objects.get_or_create(
                event=event, trigger=trigger,
                defaults={'enabled': False, 'template': template},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_event_twitch_channels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('donation', 'Donation received'), ('milestone', 'Milestone reached'), ('game_change', 'Game / run change'), ('sub', 'New subscription'), ('follow', 'New follow'), ('raid', 'Incoming raid'), ('cheer', 'Bits cheered'), ('redemption', 'Channel-point redemption')], max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('template', models.TextField(blank=True, help_text='Message posted to chat. Supports {placeholder} fields — see the per-trigger hints in /control.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_announcements', to='api.event')),
            ],
            options={
                'ordering': ['event', 'trigger'],
                'unique_together': {('event', 'trigger')},
            },
        ),
        migrations.RunPython(seed_defaults, migrations.RunPython.noop),
    ]
