# Generated by Django 5.1.5 on 2026-06-04 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_chatannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_id', models.CharField(max_length=200, unique=True)),
                ('broadcaster_id', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('winning_outcome_id', models.CharField(blank=True, max_length=200)),
                ('window_seconds', models.PositiveIntegerField(default=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.event')),
            ],
            options={
                'verbose_name': 'Twitch prediction',
                'ordering': ['-created_at'],
            },
        ),
    ]
