# Generated by Django 5.1.5 on 2026-06-04 08:07

import django.db.models.deletion
from django.db import migrations, models

_DEFAULT_CTA = (
    '💜 Enjoying the run? Help us smash the goal for {charity} — '
    'donate here: {donate_url}'
)


def seed_donation_cta(apps, schema_editor):
    Event = apps.get_model('api', 'Event')
    RecurringChatMessage = apps.get_model('api', 'RecurringChatMessage')
    for event in Event.objects.all():
        if not RecurringChatMessage.objects.filter(event=event).exists():
            RecurringChatMessage.objects.create(
                event=event, label='Donation CTA', template=_DEFAULT_CTA,
                interval_minutes=15, only_when_live=True, enabled=False,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_twitchprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Operator label (e.g. "Donation CTA"). Not posted.', max_length=80)),
                ('template', models.TextField()),
                ('interval_minutes', models.PositiveIntegerField(default=15, help_text='Minimum minutes between posts.')),
                ('only_when_live', models.BooleanField(default=True, help_text='Only post while the primary channel is live on Twitch.')),
                ('enabled', models.BooleanField(default=False)),
                ('last_posted_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_chat_messages', to='api.event')),
            ],
            options={
                'ordering': ['event', 'order', 'id'],
            },
        ),
        migrations.RunPython(seed_donation_cta, migrations.RunPython.noop),
    ]
