# Generated by Django 5.1.5 on 2026-06-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_recurringchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatannouncement',
            name='announcement_color',
            field=models.CharField(choices=[('primary', 'Channel accent'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange'), ('purple', 'Purple')], default='primary', help_text='Highlight colour when posted as an announcement.', max_length=10),
        ),
        migrations.AddField(
            model_name='chatannouncement',
            name='as_announcement',
            field=models.BooleanField(default=False, help_text='Post as a highlighted Twitch /announce (needs moderator:manage:announcements) instead of a normal message.'),
        ),
    ]
