# Generated by Django 5.1.5 on 2026-06-04 08:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_chatannouncement_announcement_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoutoutConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('shout_donations', models.BooleanField(default=True)),
                ('shout_raids', models.BooleanField(default=True)),
                ('min_donation_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Only shout out donors who gave at least this much.', max_digits=10)),
                ('only_when_live', models.BooleanField(default=True)),
                ('global_cooldown_seconds', models.PositiveIntegerField(default=120, help_text='Min seconds between any two shoutouts (Twitch ≥120).')),
                ('target_cooldown_seconds', models.PositiveIntegerField(default=3600, help_text='Min seconds before shouting the same channel again.')),
                ('max_age_minutes', models.PositiveIntegerField(default=30, help_text='Drop queued shoutouts older than this (stale).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shoutout_config', to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='ShoutoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_login', models.CharField(max_length=50)),
                ('target_display', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(choices=[('donation', 'Donation'), ('raid', 'Raid'), ('manual', 'Manual')], default='manual', max_length=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('canceled', 'Canceled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoutout_requests', to='api.event')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='api_shoutou_event_i_61e253_idx')],
            },
        ),
    ]
