# Generated by Django 5.1.5 on 2026-06-04 08:41

from django.db import migrations, models

_JOBS = [
    ('poll_donations', 'Poll donations', 'poll_donations',
     'Pull recent Tiltify / JustGiving / Twitch Charity donations.'),
    ('post_chat_reminders', 'Recurring chat messages', 'post_chat_reminders',
     'Post due recurring chat messages (e.g. the donation CTA).'),
    ('process_shoutouts', 'Process shoutouts', 'process_shoutouts',
     'Send the next due Twitch shoutout from the queue (cooldown-managed).'),
]


def seed_jobs(apps, schema_editor):
    ScheduledJob = apps.get_model('api', 'ScheduledJob')
    for key, label, command, description in _JOBS:
        ScheduledJob.objects.get_or_create(
            key=key,
            defaults={'label': label, 'command': command,
                      'description': description, 'enabled': False,
                      'interval_seconds': 60},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_shoutoutconfig_shoutoutrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('command', models.CharField(help_text='manage.py command + args, e.g. "poll_donations --twitch".', max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('enabled', models.BooleanField(default=False)),
                ('interval_seconds', models.PositiveIntegerField(default=60)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=20)),
                ('last_output', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.RunPython(seed_jobs, migrations.RunPython.noop),
    ]
