# Generated by Django 5.1.5 on 2026-06-04 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_scheduledjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_id', models.CharField(blank=True, help_text='Twitch custom-reward id (preferred match). Blank → match by title.', max_length=100)),
                ('reward_title', models.CharField(help_text='Reward name — shown in the panel and used to match when no id.', max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_mappings', to='api.event')),
            ],
            options={
                'ordering': ['event', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RewardAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('chat', 'Post chat message'), ('shoutout', 'Shout out the redeemer'), ('death_counter', 'Adjust death counter')], max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.rewardmapping')),
            ],
            options={
                'ordering': ['mapping', 'order', 'id'],
            },
        ),
    ]
