# Generated by Django 5.1.5 on 2026-06-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_rewardmapping_rewardaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tick_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
