# Generated by Django 5.1.5 on 2026-06-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_schedulerheartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='twitch_title_template',
            field=models.CharField(blank=True, help_text='Optional: also set the stream title on game change. Supports {game} and {event}. Blank → leave the title alone.', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='update_twitch_category',
            field=models.BooleanField(default=False, help_text="On a game/run change, set the primary channel's Twitch category to the new game (uses Game.twitch_game_id). Needs the primary connection to have channel:manage:broadcast."),
        ),
    ]
