# Generated by Django 5.1.5 on 2026-06-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_event_twitch_title_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chestannouncersettings',
            name='tts_enabled',
            field=models.BooleanField(default=True, help_text='When true, the chest announcer reads each donation (donor, amount and message) aloud via browser TTS as the card is held up. Independent of audio_enabled, which only gates the fanfare/trigger SFX. The omnibar no longer speaks donations, so this is the primary readout — default true.'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='announced',
            field=models.BooleanField(default=False, help_text='Set once the omnibar has played the flash/celebration for this milestone. Persistent so reopening (or adding a second) OBS browser source never replays an already-celebrated milestone. Independent of reached_at — cleared by Reset so the celebration can re-arm.'),
        ),
        migrations.AlterField(
            model_name='chestannouncersettings',
            name='audio_enabled',
            field=models.BooleanField(default=False, help_text='When true, the chest announcer plays a short procedural fanfare on each donation card reveal. Default false to avoid overlapping with the spoken readout — leave off unless you want a fanfare sting under the TTS.'),
        ),
    ]
