# Generated by Django 5.1.5 on 2026-06-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_chestannouncersettings_tts_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpage',
            name='total_currency',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='donationpage',
            name='total_donation_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationpage',
            name='total_raised',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='donationpage',
            name='total_status',
            field=models.CharField(blank=True, help_text='Platform page status, e.g. JustGiving "Active" / "Completed".', max_length=40),
        ),
        migrations.AddField(
            model_name='donationpage',
            name='total_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
