# Generated by Django 5.1.5 on 2026-06-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_donationpage_total_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardaction',
            name='action_type',
            field=models.CharField(choices=[('chat', 'Post chat message'), ('shoutout', 'Shout out the redeemer'), ('death_counter', 'Adjust death counter'), ('webhook', 'Call a webhook (HTTP)'), ('alert', 'On-stream alert + sound')], max_length=20),
        ),
    ]
