"""`python manage.py populate_zelda_data` — seeds the database with canonical
Zelda titles and a representative item checklist per game.

Idempotent: re-running upserts by title/name. Safe to call repeatedly.

Item icons live under `frontend/public/assets/img/game-items/<slug>/` and
are referenced as site-relative URLs so the OBS browser sources and the
React control panel resolve them straight from the static host.
"""
from __future__ import annotations

from urllib.parse import quote

from django.core.management.base import BaseCommand

from api import models


def _item_image_url(slug: str, filename: str) -> str:
    """Build a site-relative URL into the frontend assets folder.

    `filename` may contain spaces, apostrophes, parens, ampersands etc.
    Encode it so browsers don't have to guess.
    """
    if not filename:
        return ''
    return f'/assets/img/game-items/{slug}/{quote(filename)}'


# Each game gets: title, platform, layout_type, default_play_minutes, year,
# `slug` (frontend asset folder short — e.g. 'oot'), and a list of canonical
# items (name, category, image filename within the slug folder; '' = no art).
GAMES: list[dict] = [
    {
        'title': 'The Legend of Zelda',
        'platform': 'NES',
        'layout_type': '4x3',
        'default_play_minutes': 180,
        'release_year': 1986,
        'slug': '',  # no asset folder yet for LoZ
        'items': [
            ('Wooden Sword', 'weapon', ''),
            ('White Sword', 'weapon', ''),
            ('Magical Sword', 'weapon', ''),
            ('Wooden Boomerang', 'weapon', ''),
            ('Magical Boomerang', 'weapon', ''),
            ('Bombs', 'weapon', ''),
            ('Bow', 'weapon', ''),
            ('Magical Rod', 'weapon', ''),
            ('Blue Candle', 'key-item', ''),
            ('Red Candle', 'key-item', ''),
            ('Recorder', 'key-item', ''),
            ('Power Bracelet', 'key-item', ''),
            ('Raft', 'key-item', ''),
            ('Step Ladder', 'key-item', ''),
            ('Magic Book', 'key-item', ''),
            ('Red Ring', 'key-item', ''),
            ('Blue Ring', 'key-item', ''),
            ('Triforce of Wisdom', 'key-item', ''),
        ],
    },
    {
        'title': 'Zelda II: The Adventure of Link',
        'platform': 'NES',
        'layout_type': '4x3',
        'default_play_minutes': 240,
        'release_year': 1987,
        'slug': 'aol',
        'items': [
            ('Candle', 'key-item', 'TAoL_Candle_Sprite.png'),
            ('Handy Glove', 'key-item', 'TAoL_Handy_Glove_Sprite.png'),
            ('Raft', 'key-item', 'TAoL_Raft_Sprite.png'),
            ('Boots', 'key-item', 'TAoL_Boots_Sprite.png'),
            ('Flute', 'key-item', 'TAoL_Flute_Sprite.png'),
            ('Cross', 'key-item', 'TAoL_Cross_Sprite.png'),
            ('Magical Key', 'key-item', 'TAoL_Magical_Key_Sprite.png'),
            ('Hammer', 'key-item', 'TAoL_Hammer_Sprite.png'),
            ('Magic Container', 'heart-piece', 'TAoL_Magic_Bowl_Sprite.png'),
            ('Heart Container', 'heart-piece', 'TAoL_Bowl_of_Hearts_Sprite.png'),
            ('Shield Spell', 'song', 'TAoL_Shield_(Magic)_Artwork.png'),
            ('Jump Spell', 'song', 'TAoL_Jump_Artwork.png'),
            ('Life Spell', 'song', 'TAoL_Life_Artwork_2.png'),
            ('Fairy Spell', 'song', 'TAoL_Fairy_Artwork.png'),
            ('Fire Spell', 'song', 'TAoL_Fire_Artwork.png'),
            ('Reflect Spell', 'song', 'TAoL_Reflect_Artwork.png'),
            ('Spell Spell', 'song', 'TAoL_Spell_Artwork.png'),
            ('Thunder Spell', 'song', 'TAoL_Thunder_Artwork.png'),
        ],
    },
    {
        'title': 'The Legend of Zelda: A Link to the Past',
        'platform': 'SNES',
        'layout_type': '4x3',
        'default_play_minutes': 600,
        'release_year': 1991,
        'slug': 'lttp',
        'items': [
            ('Master Sword', 'weapon', 'ALttP_Master_Sword_Sprite.png'),
            ('Tempered Sword', 'weapon', 'ALttP_Master_Sword_Lv2_Sprite.png'),
            ('Golden Sword', 'weapon', 'ALttP_Master_Sword_Lv3_Sprite.png'),
            ('Fire Rod', 'weapon', 'FireRod.png'),
            ('Ice Rod', 'weapon', 'ALttP_Ice_Rod_Sprite.png'),
            ('Bombos Medallion', 'weapon', 'ALttP_Bombos_Medallion_Sprite.png'),
            ('Ether Medallion', 'weapon', 'Ether.png'),
            ('Quake Medallion', 'weapon', 'ALttP_Quake_Medallion_Sprite.png'),
            ('Bow', 'weapon', 'ALttP_Bow_&_Arrows_Sprite.png'),
            ('Hookshot', 'key-item', 'Hookshot.png'),
            ('Magic Hammer', 'key-item', 'ALttP_Hammer_Sprite.png'),
            ('Boomerang', 'weapon', 'ALttP_Boomerang_Sprite.png'),
            ('Magic Boomerang', 'weapon', 'ALttP_Magical_Boomerang_Sprite.png'),
            ('Pegasus Boots', 'key-item', 'ALttP_Pegasus_Shoes_Sprite.png'),
            ('Flippers', 'key-item', "ALttP_Zora's_Flippers_Sprite.png"),
            ('Moon Pearl', 'key-item', 'ALttP_Moon_Pearl_Sprite.png'),
            ('Power Glove', 'key-item', 'ALttP_Power_Glove_Sprite.png'),
            ("Titan's Mitt", 'key-item', "ALttP_Titan's_Mitt_Sprite.png"),
            ('Cane of Somaria', 'weapon', 'ALttP_Cane_of_Somaria_Sprite.png'),
            ('Cane of Byrna', 'weapon', 'ALttP_Cane_of_Byrna_Sprite.png'),
            ('Magic Cape', 'key-item', 'ALttP_Magic_Cape_Sprite.png'),
            ('Magic Mirror', 'key-item', 'ALttP_Magic_Mirror_Sprite.png'),
            ('Mushroom', 'key-item', 'ALttP_Mushroom_Sprite.png'),
            ('Magic Powder', 'key-item', 'ALttP_Magic_Powder_Sprite.png'),
        ],
    },
    {
        'title': "The Legend of Zelda: Link's Awakening",
        'platform': 'GB',
        'layout_type': '4x3',
        'default_play_minutes': 480,
        'release_year': 1993,
        'slug': 'lasr',
        'items': [
            ('Sword', 'weapon', '26px-LANS_Sword_Model.png'),
            ('Shield', 'key-item', '55px-LANS_Shield_Model.png'),
            ('Bow', 'weapon', '64px-LANS_Bow_Model.png'),
            ('Power Bracelet', 'key-item', '64px-LANS_Power_Bracelet_Model.png'),
            ('Hookshot', 'key-item', '64px-LANS_Hookshot_Model.png'),
            ('Pegasus Boots', 'key-item', '64px-LANS_Pegasus_Boots_Model.png'),
            ('Flippers', 'key-item', '36px-LANS_Flippers_Model.png'),
            ('Ocarina', 'key-item', '64px-LANS_Ocarina_Model.png'),
            ("Roc's Feather", 'key-item', "42px-LANS_Roc's_Feather_Model.png"),
            ('Boomerang', 'weapon', '64px-LANS_Boomerang_Model.png'),
            ('Magic Rod', 'weapon', '24px-LANS_Magic_Rod_Model.png'),
            ('Magic Powder', 'key-item', '44px-LANS_Magic_Powder_Model.png'),
            ('Shovel', 'key-item', '31px-LANS_Shovel_Model.png'),
            ('Ballad of the Wind Fish', 'song', ''),
            ("Manbo's Mambo", 'song', ''),
            ("Frog's Song of Soul", 'song', ''),
            ('Instrument: Full Moon Cello', 'key-item', '31px-LANS_Full_Moon_Cello_Model.png'),
            ('Instrument: Conch Horn', 'key-item', '64px-LANS_Conch_Horn_Model.png'),
            ("Instrument: Sea Lily's Bell", 'key-item', "42px-LANS_Sea_Lily's_Bell_Model.png"),
            ('Instrument: Surf Harp', 'key-item', '53px-LANS_Surf_Harp_Model.png'),
            ('Instrument: Wind Marimba', 'key-item', '62px-LANS_Wind_Marimba_Model.png'),
            ('Instrument: Coral Triangle', 'key-item', '51px-LANS_Coral_Triangle_Model.png'),
            ('Instrument: Organ of Evening Calm', 'key-item', '64px-LANS_Organ_of_Evening_Calm_Model.png'),
            ('Instrument: Thunder Drum', 'key-item', '52px-LANS_Thunder_Drum_Model.png'),
        ],
    },
    {
        'title': 'The Legend of Zelda: Ocarina of Time',
        'platform': 'N64',
        'layout_type': '4x3',
        'default_play_minutes': 720,
        'release_year': 1998,
        'slug': 'oot',
        'items': [
            ('Kokiri Sword', 'weapon', 'OoT3D_Kokiri_Sword_Icon.png'),
            ('Master Sword', 'weapon', 'OoT3D_Master_Sword_Icon.png'),
            ("Biggoron's Sword", 'weapon', "OoT3D_Biggoron's_Sword_Icon.png"),
            ('Slingshot', 'weapon', 'OoT3D_Fairy_Slingshot_Icon.png'),
            ('Fairy Bow', 'weapon', 'OoT3D_Fairy_Bow_Icon.png'),
            ('Bombs', 'weapon', 'OoT3D_Bomb_Icon.png'),
            ('Bombchu', 'weapon', ''),
            ('Boomerang', 'weapon', 'OoT3D_Boomerang_Icon.png'),
            ('Hookshot', 'key-item', 'OoT3D_Hookshot_Icon.png'),
            ('Longshot', 'key-item', 'OoT3D_Longshot_Icon.png'),
            ('Megaton Hammer', 'weapon', 'OoT3D_Megaton_Hammer_Icon.png'),
            ('Lens of Truth', 'key-item', 'OoT3D_Lens_of_Truth_Icon.png'),
            ('Iron Boots', 'key-item', 'OoT3D_Iron_Boots_Icon.png'),
            ('Hover Boots', 'key-item', 'OoT3D_Hover_Boots_Icon.png'),
            ('Dins Fire', 'weapon', "OoT3D_Din's_Fire_Icon.png"),
            ('Farores Wind', 'weapon', "OoT3D_Farore's_Wind_Icon.png"),
            ('Nayrus Love', 'key-item', "OoT3D_Nayru's_Love_Icon.png"),
            ('Goron Bracelet', 'key-item', 'OoT3D_Goron_Bracelet_Icon.png'),
            ('Silver Gauntlets', 'key-item', 'OoT3D_Silver_Gauntlets_Icon.png'),
            ('Golden Gauntlets', 'key-item', 'OoT3D_Golden_Gauntlets_Icon.png'),
            ('Silver Scale', 'key-item', 'OoT3D_Silver_Scale_Icon.png'),
            ('Golden Scale', 'key-item', 'OoT3D_Golden_Scale_Icon.png'),
            ('Ocarina of Time', 'key-item', 'OoT3D_Ocarina_of_Time_Icon.png'),
            ('Zeldas Lullaby', 'song', ''),
            ('Eponas Song', 'song', ''),
            ('Sarias Song', 'song', ''),
            ('Suns Song', 'song', ''),
            ('Song of Time', 'song', ''),
            ('Song of Storms', 'song', ''),
            ('Minuet of Forest', 'song', ''),
            ('Bolero of Fire', 'song', ''),
            ('Serenade of Water', 'song', ''),
            ('Nocturne of Shadow', 'song', ''),
            ('Requiem of Spirit', 'song', ''),
            ('Prelude of Light', 'song', ''),
            ('Forest Medallion', 'key-item', 'OoT3D_Forest_Medallion_Icon.png'),
            ('Fire Medallion', 'key-item', 'OoT3D_Fire_Medallion_Icon.png'),
            ('Water Medallion', 'key-item', 'OoT3D_Water_Medallion_Icon.png'),
            ('Shadow Medallion', 'key-item', 'OoT3D_Shadow_Medallion_Icon.png'),
            ('Spirit Medallion', 'key-item', 'OoT3D_Spirit_Medallion_Icon.png'),
            ('Light Medallion', 'key-item', 'OoT3D_Light_Medallion_Icon.png'),
        ],
    },
    {
        'title': "The Legend of Zelda: Majora's Mask",
        'platform': 'N64',
        'layout_type': '4x3',
        'default_play_minutes': 540,
        'release_year': 2000,
        'slug': 'mm',
        'items': [
            ('Kokiri Sword', 'weapon', 'MM3D Kokiri Sword Icon.png'),
            ('Razor Sword', 'weapon', 'MM3D Razor Sword Icon.png'),
            ('Gilded Sword', 'weapon', 'MM3D Gilded Sword Icon.png'),
            ('Heros Bow', 'weapon', "MM3D_Hero's_Bow_Icon.png"),
            ('Hookshot', 'key-item', 'MM3D Hookshot Icon.png'),
            ('Powder Keg', 'weapon', 'MM3D Powder Keg Icon.png'),
            ('Lens of Truth', 'key-item', 'MM3D Lens of Truth Icon.png'),
            ('Pictograph Box', 'key-item', 'MM3D Pictograph Box Icon.png'),
            ('Deku Mask', 'key-item', 'MM3D Deku Mask Icon.png'),
            ('Goron Mask', 'key-item', 'MM3D Goron Mask Icon.png'),
            ('Zora Mask', 'key-item', 'MM3D Zora Mask Icon.png'),
            ('Fierce Deity Mask', 'key-item', "MM3D Fierce Deity's Mask Icon.png"),
            ('Bunny Hood', 'key-item', 'MM3D Bunny Hood Icon.png'),
            ('Bremen Mask', 'key-item', 'MM3D Bremen Mask Icon.png'),
            ('Captains Hat', 'key-item', "MM3D Captain's Hat Icon.png"),
            ('Gibdo Mask', 'key-item', 'MM3D Gibdo Mask Icon.png'),
            ('Garos Mask', 'key-item', "MM3D Garo's Mask Icon.png"),
            ('Mask of Truth', 'key-item', 'MM3D Mask of Truth Icon.png'),
            ('All-Night Mask', 'key-item', 'MM3D All-Night Mask Icon.png'),
            ('Stone Mask', 'key-item', 'MM3D Stone Mask Icon.png'),
            ('Don Gero Mask', 'key-item', "MM3D Don Gero's Mask Icon.png"),
            ('Postmans Hat', 'key-item', "MM3D Postman's Hat Icon.png"),
            ('Kafeis Mask', 'key-item', "MM3D Kafei's Mask Icon.png"),
            ('Couples Mask', 'key-item', "MM3D Couple's Mask Icon.png"),
            ('Mask of Scents', 'key-item', 'MM3D Mask of Scents Icon.png'),
            ('Romanis Mask', 'key-item', "MM3D Romani's Mask Icon.png"),
            ('Circus Leaders Mask', 'key-item', "MM3D Troupe Leader's Mask Icon.png"),
            ('Kamaros Mask', 'key-item', "MM3D Kamaro's Mask Icon.png"),
            ('Blast Mask', 'key-item', 'MM3D Blast Mask Icon.png'),
            ('Great Fairys Mask', 'key-item', 'MM3D Great Fairy Mask Icon.png'),
            ('Keatons Mask', 'key-item', 'MM3D Keaton Mask Icon.png'),
            ('Song of Time', 'song', ''),
            ('Song of Healing', 'song', ''),
            ('Song of Soaring', 'song', ''),
            ('Sonata of Awakening', 'song', ''),
            ('Goron Lullaby', 'song', ''),
            ('New Wave Bossa Nova', 'song', ''),
            ('Elegy of Emptiness', 'song', ''),
            ('Oath to Order', 'song', ''),
        ],
    },
    {
        'title': 'The Legend of Zelda: The Wind Waker HD',
        'platform': 'WiiU',
        'layout_type': '16x9',
        'default_play_minutes': 720,
        'release_year': 2013,
        'slug': 'wwhd',
        'items': [
            ("Hero's Sword", 'weapon', 'Heros_Sword.png'),
            ('Master Sword', 'weapon', 'Master_Sword_(TWW).png'),
            ("Hero's Shield", 'key-item', 'Heros_Shield_(TWW).png'),
            ('Mirror Shield', 'key-item', 'Mirror_Shield_(TWW).png'),
            ('Telescope', 'key-item', 'Le_telescope.png'),
            ('Sail', 'key-item', 'Sail.png'),
            ('Wind Waker', 'key-item', 'WindWaker_Large.png'),
            ('Grappling Hook', 'key-item', 'Grappling_Hook_(The_Wind_Waker).png'),
            ('Boomerang', 'weapon', 'TWW_Boomerang.png'),
            ("Hero's Bow", 'weapon', 'Heros_Bow_(TWW).png'),
            ('Hookshot', 'key-item', 'Hookshot_(TWW).png'),
            ('Skull Hammer', 'weapon', 'Skull_Hammer_(TWW).png'),
            ('Deku Leaf', 'key-item', 'DekuLeaf_Large.png'),
            ('Iron Boots', 'key-item', 'Iron_Boots_(TWW).png'),
            ('Power Bracelets', 'key-item', 'Power_Bracelets_(WW).png'),
            ("Pirate's Charm", 'key-item', 'Pirates_Charm.png'),
            ('Picto Box', 'key-item', 'Picto_Box_(TWW).png'),
            ('Bombs', 'weapon', 'Bomb_(TWW).png'),
            ("Wind's Requiem", 'song', ''),
            ('Ballad of Gales', 'song', ''),
            ('Song of Passing', 'song', ''),
            ("Earth God's Lyric", 'song', ''),
            ("Wind God's Aria", 'song', ''),
            ('Triforce Shard 1', 'key-item', 'Triforce_Shard_1_(TWW).png'),
            ('Triforce Shard 2', 'key-item', 'Triforce_Shard_2_(TWW).png'),
            ('Triforce Shard 3', 'key-item', 'Triforce_Shard_3_(TWW).png'),
            ('Triforce Shard 4', 'key-item', 'Triforce_Shard_4_(TWW).png'),
            ('Triforce Shard 5', 'key-item', 'Triforce_Shard_5_(TWW).png'),
            ('Triforce Shard 6', 'key-item', 'Triforce_Shard_6_(TWW).png'),
            ('Triforce Shard 7', 'key-item', 'Triforce_Shard_7_(TWW).png'),
            ('Triforce Shard 8', 'key-item', 'Triforce_Shard_8_(TWW).png'),
        ],
    },
    {
        'title': 'The Legend of Zelda: Twilight Princess',
        'platform': 'GC',
        'layout_type': '16x9',
        'default_play_minutes': 900,
        'release_year': 2006,
        'slug': '',  # no asset folder yet for TP
        'items': [
            ('Ordon Sword', 'weapon', ''),
            ('Master Sword', 'weapon', ''),
            ('Ordon Shield', 'key-item', ''),
            ('Hylian Shield', 'key-item', ''),
            ('Bombs', 'weapon', ''),
            ('Slingshot', 'weapon', ''),
            ('Boomerang', 'weapon', ''),
            ('Iron Boots', 'key-item', ''),
            ("Hero's Bow", 'weapon', ''),
            ('Clawshot', 'key-item', ''),
            ('Double Clawshot', 'key-item', ''),
            ('Spinner', 'weapon', ''),
            ('Ball and Chain', 'weapon', ''),
            ('Dominion Rod', 'key-item', ''),
            ('Lantern', 'key-item', ''),
            ('Fishing Rod', 'key-item', ''),
            ('Horse Call', 'key-item', ''),
            ('Hawkeye', 'key-item', ''),
            ('Fused Shadow x3', 'key-item', ''),
            ('Mirror Shard x4', 'key-item', ''),
        ],
    },
    {
        'title': 'The Legend of Zelda: Phantom Hourglass',
        'platform': 'DS',
        'layout_type': 'ds-both',
        'default_play_minutes': 540,
        'release_year': 2007,
        'slug': '',  # no asset folder yet for PH
        'items': [
            ("Oshus's Sword", 'weapon', ''),
            ('Shield', 'key-item', ''),
            ('Boomerang', 'weapon', ''),
            ('Bombs', 'weapon', ''),
            ('Bow', 'weapon', ''),
            ('Grappling Hook', 'key-item', ''),
            ('Hammer', 'weapon', ''),
            ('Phantom Hourglass', 'key-item', ''),
            ('Sand of Hours', 'key-item', ''),
            ('Cyclone Slate', 'key-item', ''),
            ('Spirit of Power', 'key-item', ''),
            ('Spirit of Wisdom', 'key-item', ''),
            ('Spirit of Courage', 'key-item', ''),
        ],
    },
    {
        'title': 'The Legend of Zelda: Spirit Tracks',
        'platform': 'DS',
        'layout_type': 'ds-both',
        'default_play_minutes': 600,
        'release_year': 2009,
        'slug': 'st',
        'items': [
            ('Recruit Sword', 'weapon', 'ST_Recruit_Sword_Menu_Sprite.png'),
            ('Master Sword', 'weapon', 'LokomoSword.png'),
            ('Whirlwind', 'weapon', 'ST_Whirlwind.png'),
            ('Boomerang', 'weapon', 'ST_Boomerang.png'),
            ('Whip', 'weapon', 'ST_Whip_Sprite.png'),
            ('Bombs', 'weapon', 'ST_Bomb_Icon.png'),
            ('Bow', 'weapon', 'ST_Bow_Sprite.png'),
            ('Bow of Light', 'weapon', 'ST_Bow_of_Light_Sprite.png'),
            ('Spirit Flute', 'key-item', 'Spirit_flute.png'),
            ('Train Pass', 'key-item', ''),
            ('Force Gem', 'key-item', ''),
            ('Compass of Light', 'key-item', 'Compass_of_Light.png'),
            ('Rabbit Net', 'key-item', 'RabbitNet.png'),
        ],
    },
    {
        'title': 'The Legend of Zelda: Skyward Sword HD',
        'platform': 'Switch',
        'layout_type': '16x9',
        'default_play_minutes': 720,
        'release_year': 2021,
        'slug': 'ss',
        'items': [
            ('Goddess Sword', 'weapon', '26px-GoddessSword-SS-Icon.png'),
            ('Goddess Longsword', 'weapon', '26px-GoddessLongsword-SS-Icon.png'),
            ('Goddess White Sword', 'weapon', '26px-GoddessWhiteSword-SS-Icon.png'),
            ('Master Sword', 'weapon', '26px-MasterSword-SS-Icon.png'),
            ('True Master Sword', 'weapon', '26px-True-Master-Sword-Icon.png'),
            ('Wooden Shield', 'key-item', 'WoodenShield-SS-Icon.png'),
            ('Iron Shield', 'key-item', 'IronShield-SS-Icon.png'),
            ('Sacred Shield', 'key-item', '65px-SacredShield-SS-Icon.png'),
            ('Hylian Shield', 'key-item', ''),
            ('Slingshot', 'weapon', '61px-SkywardSwordSlingshot.png'),
            ('Beetle', 'key-item', '80px-SS_Beetle.png'),
            ('Bow', 'weapon', '80px-Bow-SS-Icon.png'),
            ('Bombs', 'weapon', '63px-SSBomb.png'),
            ('Whip', 'weapon', 'SS_Whip2.png'),
            ('Clawshots', 'key-item', '80px-Double-Clawshots-Model.png'),
            ('Gust Bellows', 'key-item', 'Gust_Bellow.png'),
            ('Digging Mitts', 'key-item', 'Digging-Mitts-Icon.png'),
            ('Mogma Mitts', 'key-item', 'MogmaMitts-SS-Icon.png'),
            ("Water Dragon's Scale", 'key-item', 'WaterDragonScale-SS-Icon.png'),
            ('Fireshield Earrings', 'key-item', 'FireshieldEarrings-SS-Icon.png'),
            ('Sailcloth', 'key-item', 'Sailcloth-SS-Icon.png'),
            ('Goddess Harp', 'key-item', "Goddess'sHarp-SS-Icon.png"),
            ('Ballad of the Goddess', 'song', ''),
            ("Farore's Courage", 'song', ''),
            ("Nayru's Wisdom", 'song', ''),
            ("Din's Power", 'song', ''),
            ('Song of the Hero', 'song', ''),
        ],
    },
    {
        'title': 'The Legend of Zelda: A Link Between Worlds',
        'platform': '3DS',
        'layout_type': '3ds',
        'default_play_minutes': 600,
        'release_year': 2013,
        'slug': '',  # no asset folder yet for ALBW
        'items': [
            ('Forgotten Sword', 'weapon', ''),
            ('Master Sword', 'weapon', ''),
            ('Master Sword Lv2', 'weapon', ''),
            ('Master Sword Lv3', 'weapon', ''),
            ('Bow', 'weapon', ''),
            ('Bombs', 'weapon', ''),
            ('Hookshot', 'key-item', ''),
            ('Boomerang', 'weapon', ''),
            ('Hammer', 'weapon', ''),
            ('Fire Rod', 'weapon', ''),
            ('Ice Rod', 'weapon', ''),
            ('Tornado Rod', 'weapon', ''),
            ('Sand Rod', 'weapon', ''),
            ('Pegasus Boots', 'key-item', ''),
            ('Power Glove', 'key-item', ''),
            ("Titan's Mitt", 'key-item', ''),
            ('Flippers', 'key-item', ''),
            ('Bee Net', 'key-item', ''),
            ('Stamina Scroll', 'key-item', ''),
            ('Pendant of Courage', 'key-item', ''),
            ('Pendant of Power', 'key-item', ''),
            ('Pendant of Wisdom', 'key-item', ''),
        ],
    },
    {
        'title': 'The Legend of Zelda: Breath of the Wild',
        'platform': 'Switch',
        'layout_type': '16x9',
        'default_play_minutes': 1500,
        'release_year': 2017,
        'slug': 'botw',
        'items': [
            ('Sheikah Slate', 'key-item', "40px-BotW_Sheikah_Slate_Icon.png"),
            ('Master Sword', 'weapon', 'BotW_Master_Sword_Icon.png'),
            ('Hylian Shield', 'key-item', 'BotW_Hylian_Shield_Icon.png'),
            ('Paraglider', 'key-item', '40px-BotW_Paraglider_Icon.png'),
            ('Magnesis', 'key-item', '64px-BotW_Magnesis_Rune_Icon.png'),
            ('Remote Bomb', 'key-item', '64px-BotW_Remote_Bomb_Rune_Icon.png'),
            ('Stasis', 'key-item', '64px-BotW_Stasis_Rune_Icon.png'),
            ('Cryonis', 'key-item', '64px-BotW_Cryonis_Rune_Icon.png'),
            ('Camera Rune', 'key-item', '64px-BotW_Camera_Rune_Icon.png'),
            ("Vah Ruta's Blessing", 'key-item', ''),
            ("Vah Rudania's Blessing", 'key-item', ''),
            ("Vah Medoh's Blessing", 'key-item', ''),
            ("Vah Naboris's Blessing", 'key-item', ''),
            ("Mipha's Grace", 'song', "40px-BotW_Mipha's_Grace_Icon.png"),
            ("Daruk's Protection", 'song', "50px-BotW_Daruk's_Protection_Icon.png"),
            ("Revali's Gale", 'song', "50px-BotW_Revali's_Gale_Icon.png"),
            ("Urbosa's Fury", 'song', "50px-BotW_Urbosa's_Fury_Icon.png"),
            ('Memory 1', 'key-item', ''),
            ('Memory 2', 'key-item', ''),
            ('Memory 3', 'key-item', ''),
            ('Memory 4', 'key-item', ''),
            ('Memory 5', 'key-item', ''),
            ('Memory 6', 'key-item', ''),
            ('Memory 7', 'key-item', ''),
            ('Memory 8', 'key-item', ''),
            ('Memory 9', 'key-item', ''),
            ('Memory 10', 'key-item', ''),
            ('Memory 11', 'key-item', ''),
            ('Memory 12', 'key-item', ''),
            ('Memory 13', 'key-item', ''),
        ],
    },
    {
        'title': 'The Legend of Zelda: Tears of the Kingdom',
        'platform': 'Switch',
        'layout_type': '16x9',
        'default_play_minutes': 2400,
        'release_year': 2023,
        'slug': '',  # no asset folder yet for TotK
        'items': [
            ('Purah Pad', 'key-item', ''),
            ('Master Sword', 'weapon', ''),
            ('Hylian Shield', 'key-item', ''),
            ('Paraglider', 'key-item', ''),
            ('Ultrahand', 'key-item', ''),
            ('Fuse', 'key-item', ''),
            ('Ascend', 'key-item', ''),
            ('Recall', 'key-item', ''),
            ('Autobuild', 'key-item', ''),
            ('Sage of Wind (Tulin)', 'key-item', ''),
            ('Sage of Fire (Yunobo)', 'key-item', ''),
            ('Sage of Water (Sidon)', 'key-item', ''),
            ('Sage of Lightning (Riju)', 'key-item', ''),
            ('Sage of Spirit (Mineru)', 'key-item', ''),
            ("Dragon's Tear 1", 'key-item', ''),
            ("Dragon's Tear 2", 'key-item', ''),
            ("Dragon's Tear 3", 'key-item', ''),
            ("Dragon's Tear 4", 'key-item', ''),
            ("Dragon's Tear 5", 'key-item', ''),
            ("Dragon's Tear 6", 'key-item', ''),
            ("Dragon's Tear 7", 'key-item', ''),
            ("Dragon's Tear 8", 'key-item', ''),
            ("Dragon's Tear 9", 'key-item', ''),
            ("Dragon's Tear 10", 'key-item', ''),
            ("Dragon's Tear 11", 'key-item', ''),
            ("Dragon's Tear 12", 'key-item', ''),
        ],
    },
]


class Command(BaseCommand):
    help = 'Seed canonical Zelda games + item checklists. Idempotent.'

    def handle(self, *args, **options):
        created_games = 0
        created_items = 0
        updated_items = 0
        for spec in GAMES:
            spec = dict(spec)  # local copy so re-running the command doesn't mutate the module
            items = spec.pop('items', [])
            slug = spec.pop('slug', '')
            game, was_new = models.Game.objects.update_or_create(
                title=spec['title'],
                defaults=spec,
            )
            if was_new:
                created_games += 1
            for order, (name, category, image_file) in enumerate(items):
                image_url = _item_image_url(slug, image_file)
                obj, new = models.GameItem.objects.update_or_create(
                    game=game,
                    name=name,
                    defaults={
                        'category': category,
                        'order': order,
                        'image_url': image_url,
                    },
                )
                if new:
                    created_items += 1
                else:
                    updated_items += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'Done. Games processed: {len(GAMES)} (+{created_games} new). '
                f'Items added: {created_items}, updated: {updated_items}.'
            )
        )
