"""`python manage.py populate_zelda_data` — seeds the database with canonical
Zelda titles and a representative item checklist per game.

Idempotent: re-running upserts by title/name. Safe to call repeatedly.
"""
from __future__ import annotations

from django.core.management.base import BaseCommand

from api import models


# Each game gets: title, platform, layout_type, default_play_minutes, year,
# and a list of canonical items (name + category).
GAMES: list[dict] = [
    {
        'title': 'The Legend of Zelda',
        'platform': 'NES',
        'layout_type': '4x3',
        'default_play_minutes': 180,
        'release_year': 1986,
        'items': [
            ('Wooden Sword', 'weapon'),
            ('White Sword', 'weapon'),
            ('Magical Sword', 'weapon'),
            ('Wooden Boomerang', 'weapon'),
            ('Magical Boomerang', 'weapon'),
            ('Bombs', 'weapon'),
            ('Bow', 'weapon'),
            ('Magical Rod', 'weapon'),
            ('Blue Candle', 'key-item'),
            ('Red Candle', 'key-item'),
            ('Recorder', 'key-item'),
            ('Power Bracelet', 'key-item'),
            ('Raft', 'key-item'),
            ('Step Ladder', 'key-item'),
            ('Magic Book', 'key-item'),
            ('Red Ring', 'key-item'),
            ('Blue Ring', 'key-item'),
            ('Triforce of Wisdom', 'key-item'),
        ],
    },
    {
        'title': 'Zelda II: The Adventure of Link',
        'platform': 'NES',
        'layout_type': '4x3',
        'default_play_minutes': 240,
        'release_year': 1987,
        'items': [
            ('Candle', 'key-item'),
            ('Handy Glove', 'key-item'),
            ('Raft', 'key-item'),
            ('Boots', 'key-item'),
            ('Flute', 'key-item'),
            ('Cross', 'key-item'),
            ('Magical Key', 'key-item'),
            ('Hammer', 'key-item'),
            ('Magic Container', 'heart-piece'),
            ('Heart Container', 'heart-piece'),
            ('Shield Spell', 'song'),
            ('Jump Spell', 'song'),
            ('Life Spell', 'song'),
            ('Fairy Spell', 'song'),
            ('Fire Spell', 'song'),
            ('Reflect Spell', 'song'),
            ('Spell Spell', 'song'),
            ('Thunder Spell', 'song'),
        ],
    },
    {
        'title': 'The Legend of Zelda: A Link to the Past',
        'platform': 'SNES',
        'layout_type': '4x3',
        'default_play_minutes': 600,
        'release_year': 1991,
        'items': [
            ('Master Sword', 'weapon'),
            ('Tempered Sword', 'weapon'),
            ('Golden Sword', 'weapon'),
            ('Fire Rod', 'weapon'),
            ('Ice Rod', 'weapon'),
            ('Bombos Medallion', 'weapon'),
            ('Ether Medallion', 'weapon'),
            ('Quake Medallion', 'weapon'),
            ('Bow', 'weapon'),
            ('Hookshot', 'key-item'),
            ('Magic Hammer', 'key-item'),
            ('Boomerang', 'weapon'),
            ('Magic Boomerang', 'weapon'),
            ('Pegasus Boots', 'key-item'),
            ('Flippers', 'key-item'),
            ('Moon Pearl', 'key-item'),
            ('Power Glove', 'key-item'),
            ('Titan\'s Mitt', 'key-item'),
            ('Cane of Somaria', 'weapon'),
            ('Cane of Byrna', 'weapon'),
            ('Magic Cape', 'key-item'),
            ('Magic Mirror', 'key-item'),
            ('Mushroom', 'key-item'),
            ('Magic Powder', 'key-item'),
        ],
    },
    {
        'title': 'The Legend of Zelda: Link\'s Awakening',
        'platform': 'GB',
        'layout_type': '4x3',
        'default_play_minutes': 480,
        'release_year': 1993,
        'items': [
            ('Sword', 'weapon'),
            ('Shield', 'key-item'),
            ('Bow', 'weapon'),
            ('Power Bracelet', 'key-item'),
            ('Hookshot', 'key-item'),
            ('Pegasus Boots', 'key-item'),
            ('Flippers', 'key-item'),
            ('Ocarina', 'key-item'),
            ('Roc\'s Feather', 'key-item'),
            ('Boomerang', 'weapon'),
            ('Magic Rod', 'weapon'),
            ('Magic Powder', 'key-item'),
            ('Shovel', 'key-item'),
            ('Ballad of the Wind Fish', 'song'),
            ('Manbo\'s Mambo', 'song'),
            ('Frog\'s Song of Soul', 'song'),
            ('Instrument: Full Moon Cello', 'key-item'),
            ('Instrument: Conch Horn', 'key-item'),
            ('Instrument: Sea Lily\'s Bell', 'key-item'),
            ('Instrument: Surf Harp', 'key-item'),
            ('Instrument: Wind Marimba', 'key-item'),
            ('Instrument: Coral Triangle', 'key-item'),
            ('Instrument: Organ of Evening Calm', 'key-item'),
            ('Instrument: Thunder Drum', 'key-item'),
        ],
    },
    {
        'title': 'The Legend of Zelda: Ocarina of Time',
        'platform': 'N64',
        'layout_type': '4x3',
        'default_play_minutes': 720,
        'release_year': 1998,
        'items': [
            ('Kokiri Sword', 'weapon'),
            ('Master Sword', 'weapon'),
            ('Biggoron\'s Sword', 'weapon'),
            ('Slingshot', 'weapon'),
            ('Fairy Bow', 'weapon'),
            ('Bombs', 'weapon'),
            ('Bombchu', 'weapon'),
            ('Boomerang', 'weapon'),
            ('Hookshot', 'key-item'),
            ('Longshot', 'key-item'),
            ('Megaton Hammer', 'weapon'),
            ('Lens of Truth', 'key-item'),
            ('Iron Boots', 'key-item'),
            ('Hover Boots', 'key-item'),
            ('Dins Fire', 'weapon'),
            ('Farores Wind', 'weapon'),
            ('Nayrus Love', 'key-item'),
            ('Goron Bracelet', 'key-item'),
            ('Silver Gauntlets', 'key-item'),
            ('Golden Gauntlets', 'key-item'),
            ('Silver Scale', 'key-item'),
            ('Golden Scale', 'key-item'),
            ('Ocarina of Time', 'key-item'),
            ('Zeldas Lullaby', 'song'),
            ('Eponas Song', 'song'),
            ('Sarias Song', 'song'),
            ('Suns Song', 'song'),
            ('Song of Time', 'song'),
            ('Song of Storms', 'song'),
            ('Minuet of Forest', 'song'),
            ('Bolero of Fire', 'song'),
            ('Serenade of Water', 'song'),
            ('Nocturne of Shadow', 'song'),
            ('Requiem of Spirit', 'song'),
            ('Prelude of Light', 'song'),
            ('Forest Medallion', 'key-item'),
            ('Fire Medallion', 'key-item'),
            ('Water Medallion', 'key-item'),
            ('Shadow Medallion', 'key-item'),
            ('Spirit Medallion', 'key-item'),
            ('Light Medallion', 'key-item'),
        ],
    },
    {
        'title': 'The Legend of Zelda: Majora\'s Mask',
        'platform': 'N64',
        'layout_type': '4x3',
        'default_play_minutes': 540,
        'release_year': 2000,
        'items': [
            ('Kokiri Sword', 'weapon'),
            ('Razor Sword', 'weapon'),
            ('Gilded Sword', 'weapon'),
            ('Heros Bow', 'weapon'),
            ('Hookshot', 'key-item'),
            ('Powder Keg', 'weapon'),
            ('Lens of Truth', 'key-item'),
            ('Pictograph Box', 'key-item'),
            ('Deku Mask', 'key-item'),
            ('Goron Mask', 'key-item'),
            ('Zora Mask', 'key-item'),
            ('Fierce Deity Mask', 'key-item'),
            ('Bunny Hood', 'key-item'),
            ('Bremen Mask', 'key-item'),
            ('Captains Hat', 'key-item'),
            ('Gibdo Mask', 'key-item'),
            ('Garos Mask', 'key-item'),
            ('Mask of Truth', 'key-item'),
            ('All-Night Mask', 'key-item'),
            ('Stone Mask', 'key-item'),
            ('Don Gero Mask', 'key-item'),
            ('Postmans Hat', 'key-item'),
            ('Kafeis Mask', 'key-item'),
            ('Couples Mask', 'key-item'),
            ('Mask of Scents', 'key-item'),
            ('Romanis Mask', 'key-item'),
            ('Circus Leaders Mask', 'key-item'),
            ('Kamaros Mask', 'key-item'),
            ('Blast Mask', 'key-item'),
            ('Great Fairys Mask', 'key-item'),
            ('Keatons Mask', 'key-item'),
            ('Song of Time', 'song'),
            ('Song of Healing', 'song'),
            ('Song of Soaring', 'song'),
            ('Sonata of Awakening', 'song'),
            ('Goron Lullaby', 'song'),
            ('New Wave Bossa Nova', 'song'),
            ('Elegy of Emptiness', 'song'),
            ('Oath to Order', 'song'),
        ],
    },
    {
        'title': 'The Legend of Zelda: The Wind Waker HD',
        'platform': 'WiiU',
        'layout_type': '16x9',
        'default_play_minutes': 720,
        'release_year': 2013,
        'items': [
            ('Hero\'s Sword', 'weapon'),
            ('Master Sword', 'weapon'),
            ('Hero\'s Shield', 'key-item'),
            ('Mirror Shield', 'key-item'),
            ('Telescope', 'key-item'),
            ('Sail', 'key-item'),
            ('Wind Waker', 'key-item'),
            ('Grappling Hook', 'key-item'),
            ('Boomerang', 'weapon'),
            ('Hero\'s Bow', 'weapon'),
            ('Hookshot', 'key-item'),
            ('Skull Hammer', 'weapon'),
            ('Deku Leaf', 'key-item'),
            ('Iron Boots', 'key-item'),
            ('Power Bracelets', 'key-item'),
            ('Pirate\'s Charm', 'key-item'),
            ('Picto Box', 'key-item'),
            ('Bombs', 'weapon'),
            ('Wind\'s Requiem', 'song'),
            ('Ballad of Gales', 'song'),
            ('Song of Passing', 'song'),
            ('Earth God\'s Lyric', 'song'),
            ('Wind God\'s Aria', 'song'),
            ('Triforce Shard 1', 'key-item'),
            ('Triforce Shard 2', 'key-item'),
            ('Triforce Shard 3', 'key-item'),
            ('Triforce Shard 4', 'key-item'),
            ('Triforce Shard 5', 'key-item'),
            ('Triforce Shard 6', 'key-item'),
            ('Triforce Shard 7', 'key-item'),
            ('Triforce Shard 8', 'key-item'),
        ],
    },
    {
        'title': 'The Legend of Zelda: Twilight Princess',
        'platform': 'GC',
        'layout_type': '16x9',
        'default_play_minutes': 900,
        'release_year': 2006,
        'items': [
            ('Ordon Sword', 'weapon'),
            ('Master Sword', 'weapon'),
            ('Ordon Shield', 'key-item'),
            ('Hylian Shield', 'key-item'),
            ('Bombs', 'weapon'),
            ('Slingshot', 'weapon'),
            ('Boomerang', 'weapon'),
            ('Iron Boots', 'key-item'),
            ('Hero\'s Bow', 'weapon'),
            ('Clawshot', 'key-item'),
            ('Double Clawshot', 'key-item'),
            ('Spinner', 'weapon'),
            ('Ball and Chain', 'weapon'),
            ('Dominion Rod', 'key-item'),
            ('Lantern', 'key-item'),
            ('Fishing Rod', 'key-item'),
            ('Horse Call', 'key-item'),
            ('Hawkeye', 'key-item'),
            ('Fused Shadow x3', 'key-item'),
            ('Mirror Shard x4', 'key-item'),
        ],
    },
    {
        'title': 'The Legend of Zelda: Phantom Hourglass',
        'platform': 'DS',
        'layout_type': 'ds-both',
        'default_play_minutes': 540,
        'release_year': 2007,
        'items': [
            ('Oshus\'s Sword', 'weapon'),
            ('Shield', 'key-item'),
            ('Boomerang', 'weapon'),
            ('Bombs', 'weapon'),
            ('Bow', 'weapon'),
            ('Grappling Hook', 'key-item'),
            ('Hammer', 'weapon'),
            ('Phantom Hourglass', 'key-item'),
            ('Sand of Hours', 'key-item'),
            ('Cyclone Slate', 'key-item'),
            ('Spirit of Power', 'key-item'),
            ('Spirit of Wisdom', 'key-item'),
            ('Spirit of Courage', 'key-item'),
        ],
    },
    {
        'title': 'The Legend of Zelda: Spirit Tracks',
        'platform': 'DS',
        'layout_type': 'ds-both',
        'default_play_minutes': 600,
        'release_year': 2009,
        'items': [
            ('Recruit Sword', 'weapon'),
            ('Master Sword', 'weapon'),
            ('Whirlwind', 'weapon'),
            ('Boomerang', 'weapon'),
            ('Whip', 'weapon'),
            ('Bombs', 'weapon'),
            ('Bow', 'weapon'),
            ('Bow of Light', 'weapon'),
            ('Spirit Flute', 'key-item'),
            ('Train Pass', 'key-item'),
            ('Force Gem', 'key-item'),
            ('Compass of Light', 'key-item'),
            ('Rabbit Net', 'key-item'),
        ],
    },
    {
        'title': 'The Legend of Zelda: Skyward Sword HD',
        'platform': 'Switch',
        'layout_type': '16x9',
        'default_play_minutes': 720,
        'release_year': 2021,
        'items': [
            ('Goddess Sword', 'weapon'),
            ('Goddess Longsword', 'weapon'),
            ('Goddess White Sword', 'weapon'),
            ('Master Sword', 'weapon'),
            ('True Master Sword', 'weapon'),
            ('Wooden Shield', 'key-item'),
            ('Iron Shield', 'key-item'),
            ('Sacred Shield', 'key-item'),
            ('Hylian Shield', 'key-item'),
            ('Slingshot', 'weapon'),
            ('Beetle', 'key-item'),
            ('Bow', 'weapon'),
            ('Bombs', 'weapon'),
            ('Whip', 'weapon'),
            ('Clawshots', 'key-item'),
            ('Gust Bellows', 'key-item'),
            ('Digging Mitts', 'key-item'),
            ('Mogma Mitts', 'key-item'),
            ('Water Dragon\'s Scale', 'key-item'),
            ('Fireshield Earrings', 'key-item'),
            ('Sailcloth', 'key-item'),
            ('Goddess Harp', 'key-item'),
            ('Ballad of the Goddess', 'song'),
            ('Farore\'s Courage', 'song'),
            ('Nayru\'s Wisdom', 'song'),
            ('Din\'s Power', 'song'),
            ('Song of the Hero', 'song'),
        ],
    },
    {
        'title': 'The Legend of Zelda: A Link Between Worlds',
        'platform': '3DS',
        'layout_type': '3ds',
        'default_play_minutes': 600,
        'release_year': 2013,
        'items': [
            ('Forgotten Sword', 'weapon'),
            ('Master Sword', 'weapon'),
            ('Master Sword Lv2', 'weapon'),
            ('Master Sword Lv3', 'weapon'),
            ('Bow', 'weapon'),
            ('Bombs', 'weapon'),
            ('Hookshot', 'key-item'),
            ('Boomerang', 'weapon'),
            ('Hammer', 'weapon'),
            ('Fire Rod', 'weapon'),
            ('Ice Rod', 'weapon'),
            ('Tornado Rod', 'weapon'),
            ('Sand Rod', 'weapon'),
            ('Pegasus Boots', 'key-item'),
            ('Power Glove', 'key-item'),
            ('Titan\'s Mitt', 'key-item'),
            ('Flippers', 'key-item'),
            ('Bee Net', 'key-item'),
            ('Stamina Scroll', 'key-item'),
            ('Pendant of Courage', 'key-item'),
            ('Pendant of Power', 'key-item'),
            ('Pendant of Wisdom', 'key-item'),
        ],
    },
    {
        'title': 'The Legend of Zelda: Breath of the Wild',
        'platform': 'Switch',
        'layout_type': '16x9',
        'default_play_minutes': 1500,
        'release_year': 2017,
        'items': [
            ('Sheikah Slate', 'key-item'),
            ('Master Sword', 'weapon'),
            ('Hylian Shield', 'key-item'),
            ('Paraglider', 'key-item'),
            ('Magnesis', 'key-item'),
            ('Remote Bomb', 'key-item'),
            ('Stasis', 'key-item'),
            ('Cryonis', 'key-item'),
            ('Camera Rune', 'key-item'),
            ('Vah Ruta\'s Blessing', 'key-item'),
            ('Vah Rudania\'s Blessing', 'key-item'),
            ('Vah Medoh\'s Blessing', 'key-item'),
            ('Vah Naboris\'s Blessing', 'key-item'),
            ('Mipha\'s Grace', 'song'),
            ('Daruk\'s Protection', 'song'),
            ('Revali\'s Gale', 'song'),
            ('Urbosa\'s Fury', 'song'),
            ('Memory 1', 'key-item'),
            ('Memory 2', 'key-item'),
            ('Memory 3', 'key-item'),
            ('Memory 4', 'key-item'),
            ('Memory 5', 'key-item'),
            ('Memory 6', 'key-item'),
            ('Memory 7', 'key-item'),
            ('Memory 8', 'key-item'),
            ('Memory 9', 'key-item'),
            ('Memory 10', 'key-item'),
            ('Memory 11', 'key-item'),
            ('Memory 12', 'key-item'),
            ('Memory 13', 'key-item'),
        ],
    },
    {
        'title': 'The Legend of Zelda: Tears of the Kingdom',
        'platform': 'Switch',
        'layout_type': '16x9',
        'default_play_minutes': 2400,
        'release_year': 2023,
        'items': [
            ('Purah Pad', 'key-item'),
            ('Master Sword', 'weapon'),
            ('Hylian Shield', 'key-item'),
            ('Paraglider', 'key-item'),
            ('Ultrahand', 'key-item'),
            ('Fuse', 'key-item'),
            ('Ascend', 'key-item'),
            ('Recall', 'key-item'),
            ('Autobuild', 'key-item'),
            ('Sage of Wind (Tulin)', 'key-item'),
            ('Sage of Fire (Yunobo)', 'key-item'),
            ('Sage of Water (Sidon)', 'key-item'),
            ('Sage of Lightning (Riju)', 'key-item'),
            ('Sage of Spirit (Mineru)', 'key-item'),
            ('Dragon\'s Tear 1', 'key-item'),
            ('Dragon\'s Tear 2', 'key-item'),
            ('Dragon\'s Tear 3', 'key-item'),
            ('Dragon\'s Tear 4', 'key-item'),
            ('Dragon\'s Tear 5', 'key-item'),
            ('Dragon\'s Tear 6', 'key-item'),
            ('Dragon\'s Tear 7', 'key-item'),
            ('Dragon\'s Tear 8', 'key-item'),
            ('Dragon\'s Tear 9', 'key-item'),
            ('Dragon\'s Tear 10', 'key-item'),
            ('Dragon\'s Tear 11', 'key-item'),
            ('Dragon\'s Tear 12', 'key-item'),
        ],
    },
]


class Command(BaseCommand):
    help = 'Seed canonical Zelda games + item checklists. Idempotent.'

    def handle(self, *args, **options):
        created_games = 0
        created_items = 0
        for spec in GAMES:
            items = spec.pop('items', [])
            game, was_new = models.Game.objects.update_or_create(
                title=spec['title'],
                defaults=spec,
            )
            if was_new:
                created_games += 1
            for order, (name, category) in enumerate(items):
                _, new = models.GameItem.objects.update_or_create(
                    game=game,
                    name=name,
                    defaults={'category': category, 'order': order},
                )
                if new:
                    created_items += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'Done. Games processed: {len(GAMES)} (+{created_games} new). '
                f'Items added: {created_items}.'
            )
        )
